export const amtrakRoutes = [
  {
    route_id: 40751,
    route_long_name: 'Acela',
  },
  {
    route_id: 95,
    route_long_name: 'Adirondack',
  },
  {
    route_id: 60,
    route_long_name: 'Amtrak Cascades',
  },
  {
    route_id: 41042,
    route_long_name: 'Amtrak Hartford Line',
  },
  {
    route_id: 77,
    route_long_name: 'Auto Train',
  },
  {
    route_id: 42948,
    route_long_name: 'Berkshire Flyer',
  },
  {
    route_id: 71,
    route_long_name: 'Blue Water',
  },
  {
    route_id: 96,
    route_long_name: 'California Zephyr',
  },
  {
    route_id: 84,
    route_long_name: 'Capitol Corridor',
  },
  {
    route_id: 36922,
    route_long_name: 'Capitol Limited',
  },
  {
    route_id: 58,
    route_long_name: 'Cardinal',
  },
  {
    route_id: 72,
    route_long_name: 'Carl Sandburg',
  },
  {
    route_id: 85,
    route_long_name: 'Carolinian',
  },
  {
    route_id: 62,
    route_long_name: 'City Of New Orleans',
  },
  {
    route_id: 36924,
    route_long_name: 'Coast Starlight',
  },
  {
    route_id: 36923,
    route_long_name: 'Crescent',
  },
  {
    route_id: 61,
    route_long_name: 'Downeaster',
  },
  {
    route_id: 75,
    route_long_name: 'Empire Builder',
  },
  {
    route_id: 36921,
    route_long_name: 'Empire Service',
  },
  {
    route_id: 36949,
    route_long_name: 'Ethan Allen Express',
  },
  {
    route_id: 86,
    route_long_name: 'Heartland Flyer',
  },
  {
    route_id: 54,
    route_long_name: 'Hiawatha Service',
  },
  {
    route_id: 56,
    route_long_name: 'Illini',
  },
  {
    route_id: 93,
    route_long_name: 'Illinois Zephyr',
  },
  {
    route_id: 94,
    route_long_name: 'Keystone Service',
  },
  {
    route_id: 81,
    route_long_name: 'Lake Shore Limited',
  },
  {
    route_id: 36926,
    route_long_name: 'Lincoln Service',
  },
  {
    route_id: 42947,
    route_long_name: 'Lincoln Service Missouri River Runner',
  },
  {
    route_id: 68,
    route_long_name: 'Maple Leaf',
  },
  {
    route_id: 36948,
    route_long_name: 'Missouri River Runner',
  },
  {
    route_id: 88,
    route_long_name: 'Northeast Regional',
  },
  {
    route_id: 78,
    route_long_name: 'Pacific Surfliner',
  },
  {
    route_id: 69,
    route_long_name: 'Palmetto',
  },
  {
    route_id: 64,
    route_long_name: 'Pennsylvanian',
  },
  {
    route_id: 55,
    route_long_name: 'Pere Marquette',
  },
  {
    route_id: 79,
    route_long_name: 'Piedmont',
  },
  {
    route_id: 63,
    route_long_name: 'Saluki',
  },
  {
    route_id: 26025,
    route_long_name: 'San Joaquins',
  },
  {
    route_id: 91,
    route_long_name: 'Silver Meteor',
  },
  {
    route_id: 70,
    route_long_name: 'Silver Star',
  },
  {
    route_id: 51,
    route_long_name: 'Southwest Chief',
  },
  {
    route_id: 36930,
    route_long_name: 'Sunset Limited',
  },
  {
    route_id: 87,
    route_long_name: 'Texas Eagle',
  },
  {
    route_id: 41044,
    route_long_name: 'Valley Flyer',
  },
  {
    route_id: 90,
    route_long_name: 'Vermonter',
  },
  {
    route_id: 80,
    route_long_name: 'Wolverine',
  },
]
export const amtrakStations = [
  {
    stop_id: "ABA",
    state: "",
    stop_short_name: "Albany International Airport",
  },
  {
    stop_id: "ABB",
    state: "",
    stop_short_name: "Abbotsford-Colby",
  },
  {
    stop_id: "ABE",
    state: "MD",
    stop_short_name: "Aberdeen",
  },
  {
    stop_id: "ABQ",
    state: "NM",
    stop_short_name: "Albuquerque",
  },
  {
    stop_id: "ACA",
    state: "CA",
    stop_short_name: "Antioch-Pittsburg",
  },
  {
    stop_id: "ACD",
    state: "MO",
    stop_short_name: "Arcadia Valley",
  },
  {
    stop_id: "ADM",
    state: "OK",
    stop_short_name: "Ardmore",
  },
  {
    stop_id: "AKY",
    state: "KY",
    stop_short_name: "Ashland",
  },
  {
    stop_id: "ALB",
    state: "NY",
    stop_short_name: "Albany-Rensselaer",
  },
  {
    stop_id: "ALC",
    state: "OH",
    stop_short_name: "Alliance",
  },
  {
    stop_id: "ALD",
    state: "WV",
    stop_short_name: "Alderson",
  },
  {
    stop_id: "ALI",
    state: "MI",
    stop_short_name: "Albion",
  },
  {
    stop_id: "ALM",
    state: "",
    stop_short_name: "Alpena",
  },
  {
    stop_id: "ALN",
    state: "IL",
    stop_short_name: "Alton",
  },
  {
    stop_id: "ALP",
    state: "TX",
    stop_short_name: "Alpine",
  },
  {
    stop_id: "ALT",
    state: "PA",
    stop_short_name: "Altoona",
  },
  {
    stop_id: "ALX",
    state: "VA",
    stop_short_name: "Alexandria",
  },
  {
    stop_id: "ALY",
    state: "OR",
    stop_short_name: "Albany",
  },
  {
    stop_id: "AMS",
    state: "NY",
    stop_short_name: "Amsterdam",
  },
  {
    stop_id: "ANA",
    state: "CA",
    stop_short_name: "Anaheim",
  },
  {
    stop_id: "APP",
    state: "",
    stop_short_name: "Appleton",
  },
  {
    stop_id: "ARB",
    state: "MI",
    stop_short_name: "Ann Arbor",
  },
  {
    stop_id: "ARC",
    state: "",
    stop_short_name: "Arcata",
  },
  {
    stop_id: "ARD",
    state: "PA",
    stop_short_name: "Ardmore",
  },
  {
    stop_id: "ARK",
    state: "AR",
    stop_short_name: "Arkadelphia",
  },
  {
    stop_id: "ARN",
    state: "CA",
    stop_short_name: "Auburn",
  },
  {
    stop_id: "ASD",
    state: "VA",
    stop_short_name: "Ashland",
  },
  {
    stop_id: "ATL",
    state: "GA",
    stop_short_name: "Atlanta",
  },
  {
    stop_id: "ATN",
    state: "AL",
    stop_short_name: "Anniston",
  },
  {
    stop_id: "AUS",
    state: "TX",
    stop_short_name: "Austin",
  },
  {
    stop_id: "AVO",
    state: "",
    stop_short_name: "Avon",
  },
  {
    stop_id: "AWN",
    state: "",
    stop_short_name: "Allentown",
  },
  {
    stop_id: "BAH",
    state: "",
    stop_short_name: "Bath",
  },
  {
    stop_id: "BAL",
    state: "MD",
    stop_short_name: "Baltimore Penn",
  },
  {
    stop_id: "BAM",
    state: "MI",
    stop_short_name: "Bangor",
  },
  {
    stop_id: "BAR",
    state: "CA",
    stop_short_name: "Barstow",
  },
  {
    stop_id: "BBY",
    state: "MA",
    stop_short_name: "Boston Back Bay",
  },
  {
    stop_id: "BCV",
    state: "VA",
    stop_short_name: "Burke Centre",
  },
  {
    stop_id: "BCY",
    state: "",
    stop_short_name: "Bay City",
  },
  {
    stop_id: "BDN",
    state: "",
    stop_short_name: "Brandon",
  },
  {
    stop_id: "BDT",
    state: "",
    stop_short_name: "Bradenton",
  },
  {
    stop_id: "BEL",
    state: "WA",
    stop_short_name: "Bellingham",
  },
  {
    stop_id: "BEN",
    state: "AZ",
    stop_short_name: "Benson",
  },
  {
    stop_id: "BER",
    state: "CT",
    stop_short_name: "Berlin",
  },
  {
    stop_id: "BET",
    state: "",
    stop_short_name: "South Beloit",
  },
  {
    stop_id: "BFD",
    state: "CA",
    stop_short_name: "Bakersfield",
  },
  {
    stop_id: "BFW",
    state: "",
    stop_short_name: "Buffalo",
  },
  {
    stop_id: "BFX",
    state: "NY",
    stop_short_name: "Buffalo Exchange St",
  },
  {
    stop_id: "BHM",
    state: "AL",
    stop_short_name: "Birmingham",
  },
  {
    stop_id: "BIR",
    state: "",
    stop_short_name: "Big Run",
  },
  {
    stop_id: "BKY",
    state: "CA",
    stop_short_name: "Berkeley",
  },
  {
    stop_id: "BLF",
    state: "VT",
    stop_short_name: "Bellows Falls",
  },
  {
    stop_id: "BLK",
    state: "",
    stop_short_name: "Blacksburg",
  },
  {
    stop_id: "BLS",
    state: "",
    stop_short_name: "Blairsville",
  },
  {
    stop_id: "BMT",
    state: "TX",
    stop_short_name: "Beaumont",
  },
  {
    stop_id: "BNC",
    state: "NC",
    stop_short_name: "Burlington",
  },
  {
    stop_id: "BND",
    state: "",
    stop_short_name: "Bend",
  },
  {
    stop_id: "BNG",
    state: "WA",
    stop_short_name: "Bingen-White Salmon",
  },
  {
    stop_id: "BNL",
    state: "IL",
    stop_short_name: "Bloomington-Normal",
  },
  {
    stop_id: "BOI",
    state: "",
    stop_short_name: "Boise",
  },
  {
    stop_id: "BON",
    state: "MA",
    stop_short_name: "Boston North",
  },
  {
    stop_id: "BOS",
    state: "MA",
    stop_short_name: "Boston South",
  },
  {
    stop_id: "BRA",
    state: "VT",
    stop_short_name: "Brattleboro",
  },
  {
    stop_id: "BRH",
    state: "MS",
    stop_short_name: "Brookhaven",
  },
  {
    stop_id: "BRK",
    state: "ME",
    stop_short_name: "Brunswick",
  },
  {
    stop_id: "BRL",
    state: "IA",
    stop_short_name: "Burlington",
  },
  {
    stop_id: "BRO",
    state: "MT",
    stop_short_name: "Browning",
  },
  {
    stop_id: "BRP",
    state: "CT",
    stop_short_name: "Bridgeport",
  },
  {
    stop_id: "BTL",
    state: "MI",
    stop_short_name: "Battle Creek",
  },
  {
    stop_id: "BTN",
    state: "VT",
    stop_short_name: "Burlington",
  },
  {
    stop_id: "BUF",
    state: "NY",
    stop_short_name: "Buffalo-Depew",
  },
  {
    stop_id: "BUR",
    state: "CA",
    stop_short_name: "Burbank",
  },
  {
    stop_id: "BUV",
    state: "",
    stop_short_name: "Buena Vista",
  },
  {
    stop_id: "BVM",
    state: "",
    stop_short_name: "Beaver Marsh",
  },
  {
    stop_id: "BWI",
    state: "MD",
    stop_short_name: "BWI Airport",
  },
  {
    stop_id: "BYN",
    state: "OH",
    stop_short_name: "Bryan",
  },
  {
    stop_id: "CAM",
    state: "SC",
    stop_short_name: "Camden",
  },
  {
    stop_id: "CAS",
    state: "",
    stop_short_name: "Casper",
  },
  {
    stop_id: "CBR",
    state: "TX",
    stop_short_name: "Cleburne",
  },
  {
    stop_id: "CBS",
    state: "WI",
    stop_short_name: "Columbus",
  },
  {
    stop_id: "CDL",
    state: "IL",
    stop_short_name: "Carbondale",
  },
  {
    stop_id: "CEN",
    state: "IL",
    stop_short_name: "Centralia",
  },
  {
    stop_id: "CFD",
    state: "",
    stop_short_name: "Clearfield",
  },
  {
    stop_id: "CHI",
    state: "IL",
    stop_short_name: "Chicago U. Stn",
  },
  {
    stop_id: "CHM",
    state: "IL",
    stop_short_name: "Champaign-Urbana",
  },
  {
    stop_id: "CHN",
    state: "",
    stop_short_name: "Chiloquin",
  },
  {
    stop_id: "CHS",
    state: "SC",
    stop_short_name: "Charleston",
  },
  {
    stop_id: "CHW",
    state: "WV",
    stop_short_name: "Charleston",
  },
  {
    stop_id: "CIC",
    state: "CA",
    stop_short_name: "Chico",
  },
  {
    stop_id: "CIN",
    state: "OH",
    stop_short_name: "Cincinnati",
  },
  {
    stop_id: "CLA",
    state: "NH",
    stop_short_name: "Claremont",
  },
  {
    stop_id: "CLB",
    state: "SC",
    stop_short_name: "Columbia",
  },
  {
    stop_id: "CLE",
    state: "OH",
    stop_short_name: "Cleveland",
  },
  {
    stop_id: "CLF",
    state: "VA",
    stop_short_name: "Clifton Forge",
  },
  {
    stop_id: "CLM",
    state: "",
    stop_short_name: "Claremont",
  },
  {
    stop_id: "CLP",
    state: "VA",
    stop_short_name: "Culpeper",
  },
  {
    stop_id: "CLT",
    state: "NC",
    stop_short_name: "Charlotte",
  },
  {
    stop_id: "CML",
    state: "CA",
    stop_short_name: "Camarillo",
  },
  {
    stop_id: "CMO",
    state: "OR",
    stop_short_name: "Chemult",
  },
  {
    stop_id: "CNV",
    state: "VT",
    stop_short_name: "Castleton",
  },
  {
    stop_id: "CNY",
    state: "",
    stop_short_name: "Corning",
  },
  {
    stop_id: "COC",
    state: "CA",
    stop_short_name: "Corcoran",
  },
  {
    stop_id: "COI",
    state: "IN",
    stop_short_name: "Connersville",
  },
  {
    stop_id: "COT",
    state: "PA",
    stop_short_name: "Coatesville",
  },
  {
    stop_id: "COV",
    state: "PA",
    stop_short_name: "Connellsville",
  },
  {
    stop_id: "COX",
    state: "CA",
    stop_short_name: "Colfax",
  },
  {
    stop_id: "CPC",
    state: "",
    stop_short_name: "Cameron Park",
  },
  {
    stop_id: "CPN",
    state: "CA",
    stop_short_name: "Carpinteria",
  },
  {
    stop_id: "CRF",
    state: "IN",
    stop_short_name: "Crawfordsville",
  },
  {
    stop_id: "CRN",
    state: "IA",
    stop_short_name: "Creston",
  },
  {
    stop_id: "CRT",
    state: "NY",
    stop_short_name: "Croton-Harmon",
  },
  {
    stop_id: "CRV",
    state: "IL",
    stop_short_name: "Carlinville",
  },
  {
    stop_id: "CSN",
    state: "SC",
    stop_short_name: "Clemson",
  },
  {
    stop_id: "CSO",
    state: "",
    stop_short_name: "Crescent",
  },
  {
    stop_id: "CTL",
    state: "WA",
    stop_short_name: "Centralia",
  },
  {
    stop_id: "CUM",
    state: "MD",
    stop_short_name: "Cumberland",
  },
  {
    stop_id: "CUT",
    state: "MT",
    stop_short_name: "Cut Bank",
  },
  {
    stop_id: "CVS",
    state: "VA",
    stop_short_name: "Charlottesville",
  },
  {
    stop_id: "CVT",
    state: "",
    stop_short_name: "Colchester",
  },
  {
    stop_id: "CWH",
    state: "PA",
    stop_short_name: "Cornwells Heights",
  },
  {
    stop_id: "CWT",
    state: "CA",
    stop_short_name: "Chatsworth",
  },
  {
    stop_id: "CYN",
    state: "NC",
    stop_short_name: "Cary",
  },
  {
    stop_id: "DAL",
    state: "TX",
    stop_short_name: "Dallas",
  },
  {
    stop_id: "DAN",
    state: "VA",
    stop_short_name: "Danville",
  },
  {
    stop_id: "DAV",
    state: "CA",
    stop_short_name: "Davis",
  },
  {
    stop_id: "DBI",
    state: "",
    stop_short_name: "Du Bois",
  },
  {
    stop_id: "DBP",
    state: "",
    stop_short_name: "Dublin-Pleasanton",
  },
  {
    stop_id: "DBY",
    state: "",
    stop_short_name: "Discovery Bay",
  },
  {
    stop_id: "DDG",
    state: "KS",
    stop_short_name: "Dodge City",
  },
  {
    stop_id: "DEB",
    state: "",
    stop_short_name: "DEB",
  },
  {
    stop_id: "DEM",
    state: "NM",
    stop_short_name: "Deming",
  },
  {
    stop_id: "DEN",
    state: "CO",
    stop_short_name: "Denver",
  },
  {
    stop_id: "DER",
    state: "MI",
    stop_short_name: "Dearborn",
  },
  {
    stop_id: "DET",
    state: "MI",
    stop_short_name: "Detroit",
  },
  {
    stop_id: "DFB",
    state: "FL",
    stop_short_name: "Deerfield Beach",
  },
  {
    stop_id: "DHM",
    state: "NH",
    stop_short_name: "Durham",
  },
  {
    stop_id: "DIL",
    state: "SC",
    stop_short_name: "Dillon",
  },
  {
    stop_id: "DLB",
    state: "FL",
    stop_short_name: "Delray Beach",
  },
  {
    stop_id: "DLD",
    state: "FL",
    stop_short_name: "Deland",
  },
  {
    stop_id: "DLK",
    state: "MN",
    stop_short_name: "Detroit Lakes",
  },
  {
    stop_id: "DNC",
    state: "NC",
    stop_short_name: "Durham",
  },
  {
    stop_id: "DNK",
    state: "SC",
    stop_short_name: "Denmark",
  },
  {
    stop_id: "DOA",
    state: "MI",
    stop_short_name: "Dowagiac",
  },
  {
    stop_id: "DOV",
    state: "NH",
    stop_short_name: "Dover",
  },
  {
    stop_id: "DOW",
    state: "PA",
    stop_short_name: "Downingtown",
  },
  {
    stop_id: "DQN",
    state: "IL",
    stop_short_name: "Du Quoin",
  },
  {
    stop_id: "DRD",
    state: "MI",
    stop_short_name: "Durand",
  },
  {
    stop_id: "DRT",
    state: "TX",
    stop_short_name: "Del Rio",
  },
  {
    stop_id: "DUN",
    state: "CA",
    stop_short_name: "Dunsmuir",
  },
  {
    stop_id: "DVL",
    state: "ND",
    stop_short_name: "Devils Lake",
  },
  {
    stop_id: "DWT",
    state: "IL",
    stop_short_name: "Dwight",
  },
  {
    stop_id: "DYE",
    state: "IN",
    stop_short_name: "Dyer",
  },
  {
    stop_id: "EDM",
    state: "WA",
    stop_short_name: "Edmonds",
  },
  {
    stop_id: "EFG",
    state: "IL",
    stop_short_name: "Effingham",
  },
  {
    stop_id: "EKH",
    state: "IN",
    stop_short_name: "Elkhart",
  },
  {
    stop_id: "ELK",
    state: "NV",
    stop_short_name: "Elko",
  },
  {
    stop_id: "ELP",
    state: "TX",
    stop_short_name: "El Paso",
  },
  {
    stop_id: "ELT",
    state: "PA",
    stop_short_name: "Elizabethtown",
  },
  {
    stop_id: "ELY",
    state: "OH",
    stop_short_name: "Elyria",
  },
  {
    stop_id: "EMA",
    state: "",
    stop_short_name: "Elmira",
  },
  {
    stop_id: "EMI",
    state: "",
    stop_short_name: "Escanaba",
  },
  {
    stop_id: "EMY",
    state: "CA",
    stop_short_name: "Emeryville",
  },
  {
    stop_id: "EPH",
    state: "WA",
    stop_short_name: "Ephrata",
  },
  {
    stop_id: "ERI",
    state: "PA",
    stop_short_name: "Erie",
  },
  {
    stop_id: "ESM",
    state: "MT",
    stop_short_name: "Essex",
  },
  {
    stop_id: "ESX",
    state: "VT",
    stop_short_name: "Essex Jct",
  },
  {
    stop_id: "EUG",
    state: "OR",
    stop_short_name: "Eugene",
  },
  {
    stop_id: "EVR",
    state: "WA",
    stop_short_name: "Everett",
  },
  {
    stop_id: "EWR",
    state: "NJ",
    stop_short_name: "Newark Airport",
  },
  {
    stop_id: "EXR",
    state: "NH",
    stop_short_name: "Exeter",
  },
  {
    stop_id: "EXT",
    state: "PA",
    stop_short_name: "Exton",
  },
  {
    stop_id: "FAR",
    state: "ND",
    stop_short_name: "Fargo",
  },
  {
    stop_id: "FAY",
    state: "NC",
    stop_short_name: "Fayetteville",
  },
  {
    stop_id: "FBG",
    state: "VA",
    stop_short_name: "Fredericksburg",
  },
  {
    stop_id: "FED",
    state: "NY",
    stop_short_name: "Fort Edward",
  },
  {
    stop_id: "FFV",
    state: "CA",
    stop_short_name: "Fairfield-Vacaville",
  },
  {
    stop_id: "FLG",
    state: "AZ",
    stop_short_name: "Flagstaff",
  },
  {
    stop_id: "FLN",
    state: "MI",
    stop_short_name: "Flint",
  },
  {
    stop_id: "FLO",
    state: "SC",
    stop_short_name: "Florence",
  },
  {
    stop_id: "FMD",
    state: "IA",
    stop_short_name: "Fort Madison",
  },
  {
    stop_id: "FMG",
    state: "CO",
    stop_short_name: "Fort Morgan",
  },
  {
    stop_id: "FMT",
    state: "CA",
    stop_short_name: "Fremont",
  },
  {
    stop_id: "FNO",
    state: "CA",
    stop_short_name: "Fresno",
  },
  {
    stop_id: "FRA",
    state: "MA",
    stop_short_name: "Framingham",
  },
  {
    stop_id: "FRE",
    state: "ME",
    stop_short_name: "Freeport",
  },
  {
    stop_id: "FTC",
    state: "NY",
    stop_short_name: "Ticonderoga",
  },
  {
    stop_id: "FTL",
    state: "FL",
    stop_short_name: "Fort Lauderdale",
  },
  {
    stop_id: "FTN",
    state: "KY",
    stop_short_name: "Fulton",
  },
  {
    stop_id: "FTW",
    state: "TX",
    stop_short_name: "Fort Worth",
  },
  {
    stop_id: "FUL",
    state: "CA",
    stop_short_name: "Fullerton",
  },
  {
    stop_id: "GAC",
    state: "CA",
    stop_short_name: "Santa Clara-Great America",
  },
  {
    stop_id: "GAS",
    state: "NC",
    stop_short_name: "Gastonia",
  },
  {
    stop_id: "GBB",
    state: "IL",
    stop_short_name: "Galesburg",
  },
  {
    stop_id: "GBO",
    state: "",
    stop_short_name: "Goldsboro",
  },
  {
    stop_id: "GBY",
    state: "",
    stop_short_name: "Green Bay",
  },
  {
    stop_id: "GCK",
    state: "KS",
    stop_short_name: "Garden City",
  },
  {
    stop_id: "GCN",
    state: "",
    stop_short_name: "Grand Canyon Railway Depot",
  },
  {
    stop_id: "GDL",
    state: "CA",
    stop_short_name: "Glendale",
  },
  {
    stop_id: "GFD",
    state: "MA",
    stop_short_name: "Greenfield",
  },
  {
    stop_id: "GFK",
    state: "ND",
    stop_short_name: "Grand Forks",
  },
  {
    stop_id: "GGW",
    state: "MT",
    stop_short_name: "Glasgow",
  },
  {
    stop_id: "GIL",
    state: "",
    stop_short_name: "Gilchrist",
  },
  {
    stop_id: "GJT",
    state: "CO",
    stop_short_name: "Grand Junction",
  },
  {
    stop_id: "GLE",
    state: "TX",
    stop_short_name: "Gainesville",
  },
  {
    stop_id: "GLM",
    state: "IL",
    stop_short_name: "Gilman",
  },
  {
    stop_id: "GLN",
    state: "IL",
    stop_short_name: "Glenview",
  },
  {
    stop_id: "GLP",
    state: "NM",
    stop_short_name: "Gallup",
  },
  {
    stop_id: "GNB",
    state: "PA",
    stop_short_name: "Greensburg",
  },
  {
    stop_id: "GNS",
    state: "GA",
    stop_short_name: "Gainesville",
  },
  {
    stop_id: "GOF",
    state: "",
    stop_short_name: "Florence",
  },
  {
    stop_id: "GOV",
    state: "",
    stop_short_name: "Government Camp",
  },
  {
    stop_id: "GPK",
    state: "MT",
    stop_short_name: "East Glacier Park",
  },
  {
    stop_id: "GRA",
    state: "CO",
    stop_short_name: "Granby",
  },
  {
    stop_id: "GRI",
    state: "UT",
    stop_short_name: "Green River",
  },
  {
    stop_id: "GRO",
    state: "NC",
    stop_short_name: "Greensboro",
  },
  {
    stop_id: "GRR",
    state: "MI",
    stop_short_name: "Grand Rapids",
  },
  {
    stop_id: "GRV",
    state: "SC",
    stop_short_name: "Greenville",
  },
  {
    stop_id: "GSC",
    state: "CO",
    stop_short_name: "Glenwood Springs",
  },
  {
    stop_id: "GTA",
    state: "CA",
    stop_short_name: "Goleta",
  },
  {
    stop_id: "GUA",
    state: "CA",
    stop_short_name: "Guadalupe",
  },
  {
    stop_id: "GVB",
    state: "CA",
    stop_short_name: "Grover Beach",
  },
  {
    stop_id: "GWD",
    state: "MS",
    stop_short_name: "Greenwood",
  },
  {
    stop_id: "HAM",
    state: "NC",
    stop_short_name: "Hamlet",
  },
  {
    stop_id: "HAR",
    state: "PA",
    stop_short_name: "Harrisburg",
  },
  {
    stop_id: "HAS",
    state: "NE",
    stop_short_name: "Hastings",
  },
  {
    stop_id: "HAV",
    state: "MT",
    stop_short_name: "Havre",
  },
  {
    stop_id: "HAY",
    state: "CA",
    stop_short_name: "Hayward",
  },
  {
    stop_id: "HAZ",
    state: "MS",
    stop_short_name: "Hazlehurst",
  },
  {
    stop_id: "HBG",
    state: "MS",
    stop_short_name: "Hattiesburg",
  },
  {
    stop_id: "HEM",
    state: "MO",
    stop_short_name: "Hermann",
  },
  {
    stop_id: "HER",
    state: "UT",
    stop_short_name: "Helper",
  },
  {
    stop_id: "HFD",
    state: "CT",
    stop_short_name: "Hartford",
  },
  {
    stop_id: "HFY",
    state: "WV",
    stop_short_name: "Harpers Ferry",
  },
  {
    stop_id: "HGD",
    state: "PA",
    stop_short_name: "Huntingdon",
  },
  {
    stop_id: "HGM",
    state: "",
    stop_short_name: "Highmount",
  },
  {
    stop_id: "HHL",
    state: "MA",
    stop_short_name: "Haverhill",
  },
  {
    stop_id: "HIN",
    state: "WV",
    stop_short_name: "Hinton",
  },
  {
    stop_id: "HLD",
    state: "NE",
    stop_short_name: "Holdrege",
  },
  {
    stop_id: "HLK",
    state: "MA",
    stop_short_name: "Holyoke",
  },
  {
    stop_id: "HMD",
    state: "LA",
    stop_short_name: "Hammond",
  },
  {
    stop_id: "HMI",
    state: "IN",
    stop_short_name: "Hammond-Whiting",
  },
  {
    stop_id: "HMW",
    state: "IL",
    stop_short_name: "Homewood",
  },
  {
    stop_id: "HNF",
    state: "CA",
    stop_short_name: "Hanford",
  },
  {
    stop_id: "HOL",
    state: "FL",
    stop_short_name: "Hollywood",
  },
  {
    stop_id: "HOM",
    state: "MI",
    stop_short_name: "Holland",
  },
  {
    stop_id: "HOP",
    state: "AR",
    stop_short_name: "Hope",
  },
  {
    stop_id: "HOS",
    state: "TX",
    stop_short_name: "Houston",
  },
  {
    stop_id: "HPT",
    state: "NC",
    stop_short_name: "High Point",
  },
  {
    stop_id: "HUD",
    state: "NY",
    stop_short_name: "Hudson",
  },
  {
    stop_id: "HUN",
    state: "WV",
    stop_short_name: "Huntington",
  },
  {
    stop_id: "HUT",
    state: "KS",
    stop_short_name: "Hutchinson",
  },
  {
    stop_id: "HVL",
    state: "",
    stop_short_name: "Havelock",
  },
  {
    stop_id: "IDP",
    state: "MO",
    stop_short_name: "Independence",
  },
  {
    stop_id: "IND",
    state: "IN",
    stop_short_name: "Indianapolis",
  },
  {
    stop_id: "IRV",
    state: "CA",
    stop_short_name: "Irvine",
  },
  {
    stop_id: "JAN",
    state: "MS",
    stop_short_name: "Jackson",
  },
  {
    stop_id: "JAX",
    state: "FL",
    stop_short_name: "Jacksonville",
  },
  {
    stop_id: "JEF",
    state: "MO",
    stop_short_name: "Jefferson City",
  },
  {
    stop_id: "JOL",
    state: "IL",
    stop_short_name: "Joliet",
  },
  {
    stop_id: "JSP",
    state: "GA",
    stop_short_name: "Jesup",
  },
  {
    stop_id: "JST",
    state: "PA",
    stop_short_name: "Johnstown",
  },
  {
    stop_id: "JVL",
    state: "",
    stop_short_name: "Janesville",
  },
  {
    stop_id: "JXN",
    state: "MI",
    stop_short_name: "Jackson",
  },
  {
    stop_id: "KAL",
    state: "MI",
    stop_short_name: "Kalamazoo",
  },
  {
    stop_id: "KAN",
    state: "NC",
    stop_short_name: "Kannapolis",
  },
  {
    stop_id: "KCY",
    state: "MO",
    stop_short_name: "Kansas City",
  },
  {
    stop_id: "KEE",
    state: "IL",
    stop_short_name: "Kewanee",
  },
  {
    stop_id: "KEL",
    state: "WA",
    stop_short_name: "Kelso-Longview",
  },
  {
    stop_id: "KFS",
    state: "OR",
    stop_short_name: "Klamath Falls",
  },
  {
    stop_id: "KIL",
    state: "",
    stop_short_name: "Killeen",
  },
  {
    stop_id: "KIN",
    state: "RI",
    stop_short_name: "Kingston",
  },
  {
    stop_id: "KIS",
    state: "FL",
    stop_short_name: "Kissimmee",
  },
  {
    stop_id: "KKI",
    state: "IL",
    stop_short_name: "Kankakee",
  },
  {
    stop_id: "KNC",
    state: "",
    stop_short_name: "Kinston",
  },
  {
    stop_id: "KNG",
    state: "AZ",
    stop_short_name: "Kingman",
  },
  {
    stop_id: "KTR",
    state: "SC",
    stop_short_name: "Kingstree",
  },
  {
    stop_id: "KWD",
    state: "MO",
    stop_short_name: "Kirkwood",
  },
  {
    stop_id: "LAB",
    state: "PA",
    stop_short_name: "Latrobe",
  },
  {
    stop_id: "LAF",
    state: "IN",
    stop_short_name: "Lafayette",
  },
  {
    stop_id: "LAG",
    state: "IL",
    stop_short_name: "La Grange",
  },
  {
    stop_id: "LAJ",
    state: "CO",
    stop_short_name: "La Junta",
  },
  {
    stop_id: "LAK",
    state: "FL",
    stop_short_name: "Lakeland",
  },
  {
    stop_id: "LAP",
    state: "MO",
    stop_short_name: "La Plata",
  },
  {
    stop_id: "LAU",
    state: "MS",
    stop_short_name: "Laurel",
  },
  {
    stop_id: "LAX",
    state: "CA",
    stop_short_name: "Los Angeles",
  },
  {
    stop_id: "LCH",
    state: "LA",
    stop_short_name: "Lake Charles",
  },
  {
    stop_id: "LCN",
    state: "IL",
    stop_short_name: "Lincoln",
  },
  {
    stop_id: "LDB",
    state: "NM",
    stop_short_name: "Lordsburg",
  },
  {
    stop_id: "LEE",
    state: "MO",
    stop_short_name: "Lee's Summit",
  },
  {
    stop_id: "LEW",
    state: "PA",
    stop_short_name: "Lewistown",
  },
  {
    stop_id: "LFT",
    state: "LA",
    stop_short_name: "Lafayette",
  },
  {
    stop_id: "LIB",
    state: "MT",
    stop_short_name: "Libby",
  },
  {
    stop_id: "LKL",
    state: "FL",
    stop_short_name: "Lakeland",
  },
  {
    stop_id: "LMR",
    state: "CO",
    stop_short_name: "Lamar",
  },
  {
    stop_id: "LMY",
    state: "NM",
    stop_short_name: "Lamy",
  },
  {
    stop_id: "LNC",
    state: "PA",
    stop_short_name: "Lancaster",
  },
  {
    stop_id: "LNK",
    state: "NE",
    stop_short_name: "Lincoln",
  },
  {
    stop_id: "LNS",
    state: "MI",
    stop_short_name: "East Lansing",
  },
  {
    stop_id: "LOD",
    state: "CA",
    stop_short_name: "Lodi",
  },
  {
    stop_id: "LOR",
    state: "VA",
    stop_short_name: "Lorton",
  },
  {
    stop_id: "LPE",
    state: "MI",
    stop_short_name: "Lapeer",
  },
  {
    stop_id: "LPS",
    state: "CA",
    stop_short_name: "Lompoc-Surf",
  },
  {
    stop_id: "LRC",
    state: "KS",
    stop_short_name: "Lawrence",
  },
  {
    stop_id: "LRK",
    state: "AR",
    stop_short_name: "Little Rock",
  },
  {
    stop_id: "LSE",
    state: "WI",
    stop_short_name: "La Crosse",
  },
  {
    stop_id: "LSV",
    state: "NM",
    stop_short_name: "Las Vegas",
  },
  {
    stop_id: "LTM",
    state: "",
    stop_short_name: "Lathrop-Manteca",
  },
  {
    stop_id: "LVS",
    state: "",
    stop_short_name: "Las Vegas",
  },
  {
    stop_id: "LVW",
    state: "TX",
    stop_short_name: "Longview",
  },
  {
    stop_id: "LWA",
    state: "WA",
    stop_short_name: "Leavenworth",
  },
  {
    stop_id: "LYH",
    state: "VA",
    stop_short_name: "Lynchburg",
  },
  {
    stop_id: "MAC",
    state: "IL",
    stop_short_name: "Macomb",
  },
  {
    stop_id: "MAD",
    state: "",
    stop_short_name: "Madras",
  },
  {
    stop_id: "MAL",
    state: "MT",
    stop_short_name: "Malta",
  },
  {
    stop_id: "MAT",
    state: "IL",
    stop_short_name: "Mattoon",
  },
  {
    stop_id: "MAY",
    state: "KY",
    stop_short_name: "Maysville",
  },
  {
    stop_id: "MBY",
    state: "VT",
    stop_short_name: "Middlebury",
  },
  {
    stop_id: "MCB",
    state: "MS",
    stop_short_name: "McComb",
  },
  {
    stop_id: "MCD",
    state: "CA",
    stop_short_name: "Merced",
  },
  {
    stop_id: "MCG",
    state: "TX",
    stop_short_name: "McGregor",
  },
  {
    stop_id: "MCK",
    state: "NE",
    stop_short_name: "McCook",
  },
  {
    stop_id: "MDN",
    state: "CT",
    stop_short_name: "Meriden",
  },
  {
    stop_id: "MDR",
    state: "CA",
    stop_short_name: "Madera",
  },
  {
    stop_id: "MDT",
    state: "IL",
    stop_short_name: "Mendota",
  },
  {
    stop_id: "MEI",
    state: "MS",
    stop_short_name: "Meridian",
  },
  {
    stop_id: "MEM",
    state: "TN",
    stop_short_name: "Memphis",
  },
  {
    stop_id: "MET",
    state: "NJ",
    stop_short_name: "Metropark",
  },
  {
    stop_id: "MHD",
    state: "",
    stop_short_name: "Morehead City",
  },
  {
    stop_id: "MHL",
    state: "TX",
    stop_short_name: "Marshall",
  },
  {
    stop_id: "MIA",
    state: "FL",
    stop_short_name: "Miami",
  },
  {
    stop_id: "MID",
    state: "PA",
    stop_short_name: "Middletown",
  },
  {
    stop_id: "MIN",
    state: "TX",
    stop_short_name: "Mineola",
  },
  {
    stop_id: "MIY",
    state: "",
    stop_short_name: "Middlebury",
  },
  {
    stop_id: "MJY",
    state: "PA",
    stop_short_name: "Mt. Joy",
  },
  {
    stop_id: "MKA",
    state: "WI",
    stop_short_name: "Milwaukee Airport",
  },
  {
    stop_id: "MKE",
    state: "WI",
    stop_short_name: "Milwaukee Intermodal",
  },
  {
    stop_id: "MKS",
    state: "MS",
    stop_short_name: "Marks",
  },
  {
    stop_id: "MNG",
    state: "WV",
    stop_short_name: "Montgomery",
  },
  {
    stop_id: "MNY",
    state: "",
    stop_short_name: "Massena",
  },
  {
    stop_id: "MOD",
    state: "CA",
    stop_short_name: "Modesto",
  },
  {
    stop_id: "MOT",
    state: "ND",
    stop_short_name: "Minot",
  },
  {
    stop_id: "MPK",
    state: "CA",
    stop_short_name: "Moorpark",
  },
  {
    stop_id: "MPL",
    state: "",
    stop_short_name: "Mapleton",
  },
  {
    stop_id: "MPR",
    state: "VT",
    stop_short_name: "Montpelier",
  },
  {
    stop_id: "MQT",
    state: "",
    stop_short_name: "Marquette",
  },
  {
    stop_id: "MRB",
    state: "WV",
    stop_short_name: "Martinsburg",
  },
  {
    stop_id: "MRC",
    state: "AZ",
    stop_short_name: "Maricopa",
  },
  {
    stop_id: "MRV",
    state: "",
    stop_short_name: "Marysville",
  },
  {
    stop_id: "MSL",
    state: "",
    stop_short_name: "Minneapolis-St. Paul International Airport",
  },
  {
    stop_id: "MSN",
    state: "",
    stop_short_name: "Madison",
  },
  {
    stop_id: "MSP",
    state: "MN",
    stop_short_name: "St. Paul-Minneapolis",
  },
  {
    stop_id: "MSS",
    state: "VA",
    stop_short_name: "Manassas",
  },
  {
    stop_id: "MTP",
    state: "IA",
    stop_short_name: "Mt. Pleasant",
  },
  {
    stop_id: "MTR",
    state: "QC",
    stop_short_name: "Montreal Central",
  },
  {
    stop_id: "MTZ",
    state: "CA",
    stop_short_name: "Martinez",
  },
  {
    stop_id: "MVN",
    state: "AR",
    stop_short_name: "Malvern",
  },
  {
    stop_id: "MVW",
    state: "WA",
    stop_short_name: "Mt. Vernon",
  },
  {
    stop_id: "MWI",
    state: "",
    stop_short_name: "Marinette",
  },
  {
    stop_id: "MYS",
    state: "CT",
    stop_short_name: "Mystic",
  },
  {
    stop_id: "NBK",
    state: "NJ",
    stop_short_name: "New Brunswick",
  },
  {
    stop_id: "NBN",
    state: "TN",
    stop_short_name: "Newbern-Dyersburg",
  },
  {
    stop_id: "NBU",
    state: "MI",
    stop_short_name: "New Buffalo",
  },
  {
    stop_id: "NCR",
    state: "MD",
    stop_short_name: "New Carrollton",
  },
  {
    stop_id: "NDL",
    state: "CA",
    stop_short_name: "Needles",
  },
  {
    stop_id: "NEW",
    state: "KS",
    stop_short_name: "Newton",
  },
  {
    stop_id: "NFK",
    state: "VA",
    stop_short_name: "Norfolk",
  },
  {
    stop_id: "NFL",
    state: "NY",
    stop_short_name: "Niagara Falls",
  },
  {
    stop_id: "NFS",
    state: "ON",
    stop_short_name: "Niagara Falls",
  },
  {
    stop_id: "NHL",
    state: "",
    stop_short_name: "Santa Clarita-Newhall",
  },
  {
    stop_id: "NHT",
    state: "MA",
    stop_short_name: "Northampton",
  },
  {
    stop_id: "NHV",
    state: "CT",
    stop_short_name: "New Haven U. Stn",
  },
  {
    stop_id: "NIB",
    state: "LA",
    stop_short_name: "New Iberia",
  },
  {
    stop_id: "NLC",
    state: "CT",
    stop_short_name: "New London",
  },
  {
    stop_id: "NLS",
    state: "MI",
    stop_short_name: "Niles",
  },
  {
    stop_id: "NOL",
    state: "LA",
    stop_short_name: "New Orleans",
  },
  {
    stop_id: "NOR",
    state: "OK",
    stop_short_name: "Norman",
  },
  {
    stop_id: "NPN",
    state: "VA",
    stop_short_name: "Newport News",
  },
  {
    stop_id: "NPV",
    state: "IL",
    stop_short_name: "Naperville",
  },
  {
    stop_id: "NRK",
    state: "DE",
    stop_short_name: "Newark",
  },
  {
    stop_id: "NRO",
    state: "NY",
    stop_short_name: "New Rochelle",
  },
  {
    stop_id: "NWK",
    state: "NJ",
    stop_short_name: "Newark Penn",
  },
  {
    stop_id: "NYF",
    state: "",
    stop_short_name: "NYF",
  },
  {
    stop_id: "NYP",
    state: "NY",
    stop_short_name: "New York Penn",
  },
  {
    stop_id: "OAC",
    state: "CA",
    stop_short_name: "Oakland Coliseum/Airport",
  },
  {
    stop_id: "OKC",
    state: "OK",
    stop_short_name: "Oklahoma City",
  },
  {
    stop_id: "OKE",
    state: "FL",
    stop_short_name: "Okeechobee",
  },
  {
    stop_id: "OKJ",
    state: "CA",
    stop_short_name: "Oakland",
  },
  {
    stop_id: "OLT",
    state: "CA",
    stop_short_name: "San Diego-Old Town",
  },
  {
    stop_id: "OLW",
    state: "WA",
    stop_short_name: "Olympia-Lacey",
  },
  {
    stop_id: "OMA",
    state: "NE",
    stop_short_name: "Omaha",
  },
  {
    stop_id: "ONA",
    state: "CA",
    stop_short_name: "Ontario",
  },
  {
    stop_id: "ONO",
    state: "",
    stop_short_name: "Oneonta",
  },
  {
    stop_id: "ORB",
    state: "ME",
    stop_short_name: "Old Orchard Beach",
  },
  {
    stop_id: "ORC",
    state: "OR",
    stop_short_name: "Oregon City",
  },
  {
    stop_id: "ORL",
    state: "FL",
    stop_short_name: "Orlando",
  },
  {
    stop_id: "OSB",
    state: "CT",
    stop_short_name: "Old Saybrook",
  },
  {
    stop_id: "OSC",
    state: "IA",
    stop_short_name: "Osceola",
  },
  {
    stop_id: "OSD",
    state: "CA",
    stop_short_name: "Oceanside",
  },
  {
    stop_id: "OTM",
    state: "IA",
    stop_short_name: "Ottumwa",
  },
  {
    stop_id: "OXN",
    state: "CA",
    stop_short_name: "Oxnard",
  },
  {
    stop_id: "PAK",
    state: "FL",
    stop_short_name: "Palatka",
  },
  {
    stop_id: "PAO",
    state: "PA",
    stop_short_name: "Paoli",
  },
  {
    stop_id: "PAR",
    state: "PA",
    stop_short_name: "Parkesburg",
  },
  {
    stop_id: "PBF",
    state: "MO",
    stop_short_name: "Poplar Bluff",
  },
  {
    stop_id: "PCT",
    state: "IL",
    stop_short_name: "Princeton",
  },
  {
    stop_id: "PDX",
    state: "OR",
    stop_short_name: "Portland",
  },
  {
    stop_id: "PGB",
    state: "",
    stop_short_name: "Pittsburgh",
  },
  {
    stop_id: "PGH",
    state: "PA",
    stop_short_name: "Pittsburgh",
  },
  {
    stop_id: "PHA",
    state: "",
    stop_short_name: "Phoenix Sky Harbor Airport",
  },
  {
    stop_id: "PHL",
    state: "PA",
    stop_short_name: "Philadelphia",
  },
  {
    stop_id: "PHN",
    state: "PA",
    stop_short_name: "North Philadelphia",
  },
  {
    stop_id: "PIA",
    state: "",
    stop_short_name: "Peoria",
  },
  {
    stop_id: "PIC",
    state: "MS",
    stop_short_name: "Picayune",
  },
  {
    stop_id: "PIT",
    state: "MA",
    stop_short_name: "Pittsfield",
  },
  {
    stop_id: "PJC",
    state: "NJ",
    stop_short_name: "Princeton Jct",
  },
  {
    stop_id: "PLB",
    state: "NY",
    stop_short_name: "Plattsburgh",
  },
  {
    stop_id: "PLO",
    state: "IL",
    stop_short_name: "Plano",
  },
  {
    stop_id: "PLS",
    state: "",
    stop_short_name: "Pleasanton",
  },
  {
    stop_id: "PNT",
    state: "MI",
    stop_short_name: "Pontiac",
  },
  {
    stop_id: "POG",
    state: "WI",
    stop_short_name: "Portage",
  },
  {
    stop_id: "POH",
    state: "NY",
    stop_short_name: "Port Henry",
  },
  {
    stop_id: "PON",
    state: "IL",
    stop_short_name: "Pontiac",
  },
  {
    stop_id: "POR",
    state: "ME",
    stop_short_name: "Portland",
  },
  {
    stop_id: "POS",
    state: "CA",
    stop_short_name: "Pomona",
  },
  {
    stop_id: "POU",
    state: "NY",
    stop_short_name: "Poughkeepsie",
  },
  {
    stop_id: "PRB",
    state: "CA",
    stop_short_name: "Paso Robles",
  },
  {
    stop_id: "PRC",
    state: "WV",
    stop_short_name: "Prince",
  },
  {
    stop_id: "PRO",
    state: "UT",
    stop_short_name: "Provo",
  },
  {
    stop_id: "PSC",
    state: "WA",
    stop_short_name: "Pasco",
  },
  {
    stop_id: "PSN",
    state: "CA",
    stop_short_name: "Palm Springs",
  },
  {
    stop_id: "PTB",
    state: "VA",
    stop_short_name: "Petersburg",
  },
  {
    stop_id: "PTC",
    state: "",
    stop_short_name: "Petaluma",
  },
  {
    stop_id: "PTH",
    state: "MI",
    stop_short_name: "Port Huron",
  },
  {
    stop_id: "PTS",
    state: "",
    stop_short_name: "Portsmouth",
  },
  {
    stop_id: "PTU",
    state: "",
    stop_short_name: "PTU",
  },
  {
    stop_id: "PTY",
    state: "",
    stop_short_name: "PTY",
  },
  {
    stop_id: "PUL",
    state: "",
    stop_short_name: "Pullman",
  },
  {
    stop_id: "PUN",
    state: "",
    stop_short_name: "Punxsutawney",
  },
  {
    stop_id: "PUR",
    state: "OK",
    stop_short_name: "Purcell",
  },
  {
    stop_id: "PVD",
    state: "RI",
    stop_short_name: "Providence",
  },
  {
    stop_id: "PVL",
    state: "OK",
    stop_short_name: "Pauls Valley",
  },
  {
    stop_id: "PWN",
    state: "",
    stop_short_name: "Pottstown",
  },
  {
    stop_id: "PXN",
    state: "",
    stop_short_name: "North Phoenix Metro Center",
  },
  {
    stop_id: "QAN",
    state: "VA",
    stop_short_name: "Quantico",
  },
  {
    stop_id: "QCY",
    state: "IL",
    stop_short_name: "Quincy",
  },
  {
    stop_id: "RAT",
    state: "NM",
    stop_short_name: "Raton",
  },
  {
    stop_id: "RCK",
    state: "",
    stop_short_name: "Rockford",
  },
  {
    stop_id: "RDD",
    state: "CA",
    stop_short_name: "Redding",
  },
  {
    stop_id: "RDI",
    state: "",
    stop_short_name: "Reading",
  },
  {
    stop_id: "RDM",
    state: "",
    stop_short_name: "Redmond",
  },
  {
    stop_id: "RDT",
    state: "",
    stop_short_name: "Redmond",
  },
  {
    stop_id: "RDW",
    state: "MN",
    stop_short_name: "Red Wing",
  },
  {
    stop_id: "REN",
    state: "IN",
    stop_short_name: "Rensselaer",
  },
  {
    stop_id: "RGH",
    state: "NC",
    stop_short_name: "Raleigh",
  },
  {
    stop_id: "RHI",
    state: "NY",
    stop_short_name: "Rhinecliff",
  },
  {
    stop_id: "RIC",
    state: "CA",
    stop_short_name: "Richmond",
  },
  {
    stop_id: "RIV",
    state: "CA",
    stop_short_name: "Riverside",
  },
  {
    stop_id: "RKV",
    state: "MD",
    stop_short_name: "Rockville",
  },
  {
    stop_id: "RLN",
    state: "CA",
    stop_short_name: "Rocklin",
  },
  {
    stop_id: "RMN",
    state: "",
    stop_short_name: "Rochester",
  },
  {
    stop_id: "RMT",
    state: "NC",
    stop_short_name: "Rocky Mount",
  },
  {
    stop_id: "RNK",
    state: "VA",
    stop_short_name: "Roanoke",
  },
  {
    stop_id: "RNO",
    state: "NV",
    stop_short_name: "Reno",
  },
  {
    stop_id: "ROB",
    state: "",
    stop_short_name: "Rochester",
  },
  {
    stop_id: "ROC",
    state: "NY",
    stop_short_name: "Rochester",
  },
  {
    stop_id: "ROM",
    state: "NY",
    stop_short_name: "Rome",
  },
  {
    stop_id: "ROY",
    state: "MI",
    stop_short_name: "Royal Oak",
  },
  {
    stop_id: "RPH",
    state: "VT",
    stop_short_name: "Randolph",
  },
  {
    stop_id: "RSP",
    state: "NY",
    stop_short_name: "Rouses Point",
  },
  {
    stop_id: "RSV",
    state: "CA",
    stop_short_name: "Roseville",
  },
  {
    stop_id: "RTC",
    state: "",
    stop_short_name: "Rutland MVRTD Transit Cntr",
  },
  {
    stop_id: "RTE",
    state: "MA",
    stop_short_name: "Route 128",
  },
  {
    stop_id: "RTL",
    state: "IL",
    stop_short_name: "Rantoul",
  },
  {
    stop_id: "RUD",
    state: "VT",
    stop_short_name: "Rutland",
  },
  {
    stop_id: "RUG",
    state: "ND",
    stop_short_name: "Rugby",
  },
  {
    stop_id: "RVM",
    state: "VA",
    stop_short_name: "Richmond Main St",
  },
  {
    stop_id: "RVR",
    state: "VA",
    stop_short_name: "Richmond Staples Mill",
  },
  {
    stop_id: "SAB",
    state: "VT",
    stop_short_name: "St. Albans",
  },
  {
    stop_id: "SAC",
    state: "CA",
    stop_short_name: "Sacramento",
  },
  {
    stop_id: "SAF",
    state: "",
    stop_short_name: "Santa Fe",
  },
  {
    stop_id: "SAL",
    state: "NC",
    stop_short_name: "Salisbury",
  },
  {
    stop_id: "SAN",
    state: "CA",
    stop_short_name: "San Diego-Santa Fe",
  },
  {
    stop_id: "SAO",
    state: "ME",
    stop_short_name: "Saco",
  },
  {
    stop_id: "SAR",
    state: "NY",
    stop_short_name: "Saratoga Springs",
  },
  {
    stop_id: "SAS",
    state: "TX",
    stop_short_name: "San Antonio",
  },
  {
    stop_id: "SAV",
    state: "GA",
    stop_short_name: "Savannah",
  },
  {
    stop_id: "SAY",
    state: "",
    stop_short_name: "Sandy",
  },
  {
    stop_id: "SBA",
    state: "CA",
    stop_short_name: "Santa Barbara",
  },
  {
    stop_id: "SBG",
    state: "FL",
    stop_short_name: "Sebring",
  },
  {
    stop_id: "SBK",
    state: "",
    stop_short_name: "Seabrook",
  },
  {
    stop_id: "SBY",
    state: "MT",
    stop_short_name: "Shelby",
  },
  {
    stop_id: "SCC",
    state: "CA",
    stop_short_name: "Santa Clara",
  },
  {
    stop_id: "SCD",
    state: "MN",
    stop_short_name: "St. Cloud",
  },
  {
    stop_id: "SCH",
    state: "LA",
    stop_short_name: "Schriever",
  },
  {
    stop_id: "SDL",
    state: "LA",
    stop_short_name: "Slidell",
  },
  {
    stop_id: "SDY",
    state: "NY",
    stop_short_name: "Schenectady",
  },
  {
    stop_id: "SEA",
    state: "WA",
    stop_short_name: "Seattle",
  },
  {
    stop_id: "SED",
    state: "MO",
    stop_short_name: "Sedalia",
  },
  {
    stop_id: "SFA",
    state: "FL",
    stop_short_name: "Sanford",
  },
  {
    stop_id: "SFC",
    state: "",
    stop_short_name: "San Francisco",
  },
  {
    stop_id: "SGW",
    state: "",
    stop_short_name: "Saginaw",
  },
  {
    stop_id: "SHR",
    state: "",
    stop_short_name: "Shreveport SporTran Intermodal Terminal",
  },
  {
    stop_id: "SIM",
    state: "CA",
    stop_short_name: "Simi Valley",
  },
  {
    stop_id: "SJC",
    state: "CA",
    stop_short_name: "San Jose",
  },
  {
    stop_id: "SJM",
    state: "MI",
    stop_short_name: "St. Joseph",
  },
  {
    stop_id: "SKN",
    state: "CA",
    stop_short_name: "Stockton",
  },
  {
    stop_id: "SKT",
    state: "CA",
    stop_short_name: "Stockton",
  },
  {
    stop_id: "SKY",
    state: "OH",
    stop_short_name: "Sandusky",
  },
  {
    stop_id: "SLC",
    state: "UT",
    stop_short_name: "Salt Lake City",
  },
  {
    stop_id: "SLH",
    state: "",
    stop_short_name: "South Lake Tahoe",
  },
  {
    stop_id: "SLM",
    state: "OR",
    stop_short_name: "Salem",
  },
  {
    stop_id: "SLO",
    state: "CA",
    stop_short_name: "San Luis Obispo",
  },
  {
    stop_id: "SLQ",
    state: "QC",
    stop_short_name: "St-Lambert",
  },
  {
    stop_id: "SMC",
    state: "TX",
    stop_short_name: "San Marcos",
  },
  {
    stop_id: "SMD",
    state: "",
    stop_short_name: "Madison Dutch Mill Park and Ride",
  },
  {
    stop_id: "SMN",
    state: "",
    stop_short_name: "Santa Monica Pier",
  },
  {
    stop_id: "SMT",
    state: "IL",
    stop_short_name: "Summit",
  },
  {
    stop_id: "SNA",
    state: "CA",
    stop_short_name: "Santa Ana",
  },
  {
    stop_id: "SNB",
    state: "CA",
    stop_short_name: "San Bernardino",
  },
  {
    stop_id: "SNC",
    state: "CA",
    stop_short_name: "San Juan Capistrano",
  },
  {
    stop_id: "SND",
    state: "TX",
    stop_short_name: "Sanderson",
  },
  {
    stop_id: "SNP",
    state: "CA",
    stop_short_name: "San Clemente Pier",
  },
  {
    stop_id: "SNS",
    state: "CA",
    stop_short_name: "Salinas",
  },
  {
    stop_id: "SOB",
    state: "IN",
    stop_short_name: "South Bend",
  },
  {
    stop_id: "SOL",
    state: "CA",
    stop_short_name: "Solana Beach",
  },
  {
    stop_id: "SOP",
    state: "NC",
    stop_short_name: "Southern Pines",
  },
  {
    stop_id: "SPB",
    state: "SC",
    stop_short_name: "Spartanburg",
  },
  {
    stop_id: "SPG",
    state: "MA",
    stop_short_name: "Springfield",
  },
  {
    stop_id: "SPI",
    state: "IL",
    stop_short_name: "Springfield",
  },
  {
    stop_id: "SPK",
    state: "WA",
    stop_short_name: "Spokane",
  },
  {
    stop_id: "SPL",
    state: "MN",
    stop_short_name: "Staples",
  },
  {
    stop_id: "SPM",
    state: "KY",
    stop_short_name: "South Portsmouth",
  },
  {
    stop_id: "SPT",
    state: "ID",
    stop_short_name: "Sandpoint",
  },
  {
    stop_id: "SRN",
    state: "",
    stop_short_name: "Scranton",
  },
  {
    stop_id: "SSM",
    state: "NC",
    stop_short_name: "Selma",
  },
  {
    stop_id: "STA",
    state: "VA",
    stop_short_name: "Staunton",
  },
  {
    stop_id: "STI",
    state: "",
    stop_short_name: "St. Ignace",
  },
  {
    stop_id: "STL",
    state: "MO",
    stop_short_name: "St. Louis",
  },
  {
    stop_id: "STM",
    state: "CT",
    stop_short_name: "Stamford",
  },
  {
    stop_id: "STN",
    state: "ND",
    stop_short_name: "Stanley",
  },
  {
    stop_id: "STP",
    state: "",
    stop_short_name: "St. Petersburg",
  },
  {
    stop_id: "STS",
    state: "CT",
    stop_short_name: "New Haven State St",
  },
  {
    stop_id: "STW",
    state: "WA",
    stop_short_name: "Stanwood",
  },
  {
    stop_id: "SUI",
    state: "CA",
    stop_short_name: "Suisun-Fairfield",
  },
  {
    stop_id: "SVT",
    state: "WI",
    stop_short_name: "Sturtevant",
  },
  {
    stop_id: "SWB",
    state: "",
    stop_short_name: "Swansboro",
  },
  {
    stop_id: "SYR",
    state: "NY",
    stop_short_name: "Syracuse",
  },
  {
    stop_id: "TAB",
    state: "",
    stop_short_name: "Tacoma",
  },
  {
    stop_id: "TAC",
    state: "WA",
    stop_short_name: "Tacoma",
  },
  {
    stop_id: "TAY",
    state: "TX",
    stop_short_name: "Taylor",
  },
  {
    stop_id: "TCA",
    state: "GA",
    stop_short_name: "Toccoa",
  },
  {
    stop_id: "TCL",
    state: "AL",
    stop_short_name: "Tuscaloosa",
  },
  {
    stop_id: "THN",
    state: "WV",
    stop_short_name: "Thurmond",
  },
  {
    stop_id: "TOH",
    state: "WI",
    stop_short_name: "Tomah",
  },
  {
    stop_id: "TOL",
    state: "OH",
    stop_short_name: "Toledo",
  },
  {
    stop_id: "TOP",
    state: "KS",
    stop_short_name: "Topeka",
  },
  {
    stop_id: "TPA",
    state: "FL",
    stop_short_name: "Tampa",
  },
  {
    stop_id: "TPL",
    state: "TX",
    stop_short_name: "Temple",
  },
  {
    stop_id: "TRC",
    state: "",
    stop_short_name: "Tracy",
  },
  {
    stop_id: "TRE",
    state: "NJ",
    stop_short_name: "Trenton",
  },
  {
    stop_id: "TRF",
    state: "",
    stop_short_name: "Florence",
  },
  {
    stop_id: "TRI",
    state: "CO",
    stop_short_name: "Trinidad",
  },
  {
    stop_id: "TRK",
    state: "CA",
    stop_short_name: "Turlock-Denair",
  },
  {
    stop_id: "TRM",
    state: "MI",
    stop_short_name: "Troy",
  },
  {
    stop_id: "TRU",
    state: "CA",
    stop_short_name: "Truckee",
  },
  {
    stop_id: "TUK",
    state: "WA",
    stop_short_name: "Tukwila",
  },
  {
    stop_id: "TUS",
    state: "AZ",
    stop_short_name: "Tucson",
  },
  {
    stop_id: "TWO",
    state: "ON",
    stop_short_name: "Toronto",
  },
  {
    stop_id: "TXA",
    state: "AR",
    stop_short_name: "Texarkana",
  },
  {
    stop_id: "TYR",
    state: "PA",
    stop_short_name: "Tyrone",
  },
  {
    stop_id: "UCA",
    state: "NY",
    stop_short_name: "Utica",
  },
  {
    stop_id: "VAC",
    state: "BC",
    stop_short_name: "Vancouver",
  },
  {
    stop_id: "VAL",
    state: "",
    stop_short_name: "Vallejo",
  },
  {
    stop_id: "VAN",
    state: "WA",
    stop_short_name: "Vancouver",
  },
  {
    stop_id: "VAS",
    state: "",
    stop_short_name: "Livermore",
  },
  {
    stop_id: "VEC",
    state: "CA",
    stop_short_name: "Ventura",
  },
  {
    stop_id: "VIS",
    state: "",
    stop_short_name: "Visalia",
  },
  {
    stop_id: "VMW",
    state: "",
    stop_short_name: "Vallejo",
  },
  {
    stop_id: "VNC",
    state: "CA",
    stop_short_name: "Van Nuys",
  },
  {
    stop_id: "VRN",
    state: "VT",
    stop_short_name: "Ferrisburgh-Vergennes",
  },
  {
    stop_id: "VRV",
    state: "CA",
    stop_short_name: "Victorville",
  },
  {
    stop_id: "VTA",
    state: "",
    stop_short_name: "Veneta",
  },
  {
    stop_id: "WAB",
    state: "VT",
    stop_short_name: "Waterbury",
  },
  {
    stop_id: "WAC",
    state: "CA",
    stop_short_name: "Wasco",
  },
  {
    stop_id: "WAG",
    state: "",
    stop_short_name: "Wallingford",
  },
  {
    stop_id: "WAH",
    state: "MO",
    stop_short_name: "Washington",
  },
  {
    stop_id: "WAR",
    state: "MO",
    stop_short_name: "Warrensburg",
  },
  {
    stop_id: "WAS",
    state: "DC",
    stop_short_name: "Washington",
  },
  {
    stop_id: "WBG",
    state: "VA",
    stop_short_name: "Williamsburg",
  },
  {
    stop_id: "WDB",
    state: "VA",
    stop_short_name: "Woodbridge",
  },
  {
    stop_id: "WDL",
    state: "WI",
    stop_short_name: "Wisconsin Dells",
  },
  {
    stop_id: "WDO",
    state: "",
    stop_short_name: "Waldo",
  },
  {
    stop_id: "WEC",
    state: "",
    stop_short_name: "Wenatchee",
  },
  {
    stop_id: "WEM",
    state: "ME",
    stop_short_name: "Wells",
  },
  {
    stop_id: "WEN",
    state: "WA",
    stop_short_name: "Wenatchee",
  },
  {
    stop_id: "WFD",
    state: "CT",
    stop_short_name: "Wallingford",
  },
  {
    stop_id: "WFH",
    state: "MT",
    stop_short_name: "Whitefish",
  },
  {
    stop_id: "WGL",
    state: "MT",
    stop_short_name: "West Glacier",
  },
  {
    stop_id: "WHL",
    state: "NY",
    stop_short_name: "Whitehall",
  },
  {
    stop_id: "WIC",
    state: "",
    stop_short_name: "Wichita",
  },
  {
    stop_id: "WIH",
    state: "WA",
    stop_short_name: "Wishram",
  },
  {
    stop_id: "WIL",
    state: "DE",
    stop_short_name: "Wilmington",
  },
  {
    stop_id: "WIN",
    state: "MN",
    stop_short_name: "Winona",
  },
  {
    stop_id: "WIP",
    state: "CO",
    stop_short_name: "Fraser-Winter Park",
  },
  {
    stop_id: "WLC",
    state: "",
    stop_short_name: "Welches",
  },
  {
    stop_id: "WLM",
    state: "",
    stop_short_name: "Williamsport",
  },
  {
    stop_id: "WLN",
    state: "NC",
    stop_short_name: "Wilson",
  },
  {
    stop_id: "WLO",
    state: "AZ",
    stop_short_name: "Winslow",
  },
  {
    stop_id: "WLY",
    state: "RI",
    stop_short_name: "Westerly",
  },
  {
    stop_id: "WMA",
    state: "",
    stop_short_name: "Williams",
  },
  {
    stop_id: "WMH",
    state: "",
    stop_short_name: "Williams",
  },
  {
    stop_id: "WMN",
    state: "",
    stop_short_name: "Wilmington",
  },
  {
    stop_id: "WMS",
    state: "",
    stop_short_name: "Warm Springs",
  },
  {
    stop_id: "WND",
    state: "CT",
    stop_short_name: "Windsor",
  },
  {
    stop_id: "WNL",
    state: "CT",
    stop_short_name: "Windsor Locks",
  },
  {
    stop_id: "WNM",
    state: "VT",
    stop_short_name: "Windsor",
  },
  {
    stop_id: "WNN",
    state: "NV",
    stop_short_name: "Winnemucca",
  },
  {
    stop_id: "WNR",
    state: "AR",
    stop_short_name: "Walnut Ridge",
  },
  {
    stop_id: "WOB",
    state: "MA",
    stop_short_name: "Woburn",
  },
  {
    stop_id: "WOR",
    state: "MA",
    stop_short_name: "Worcester",
  },
  {
    stop_id: "WPB",
    state: "FL",
    stop_short_name: "West Palm Beach",
  },
  {
    stop_id: "WPK",
    state: "FL",
    stop_short_name: "Winter Park",
  },
  {
    stop_id: "WPN",
    state: "",
    stop_short_name: "Waupun",
  },
  {
    stop_id: "WPS",
    state: "",
    stop_short_name: "Winter Park",
  },
  {
    stop_id: "WPT",
    state: "MT",
    stop_short_name: "Wolf Point",
  },
  {
    stop_id: "WRJ",
    state: "VT",
    stop_short_name: "White River Jct",
  },
  {
    stop_id: "WRT",
    state: "",
    stop_short_name: "Watertown",
  },
  {
    stop_id: "WSP",
    state: "NY",
    stop_short_name: "Westport",
  },
  {
    stop_id: "WSS",
    state: "WV",
    stop_short_name: "White Sulphur Springs",
  },
  {
    stop_id: "WSU",
    state: "",
    stop_short_name: "Rothschild",
  },
  {
    stop_id: "WTH",
    state: "FL",
    stop_short_name: "Winter Haven",
  },
  {
    stop_id: "WTI",
    state: "IN",
    stop_short_name: "Waterloo",
  },
  {
    stop_id: "WTN",
    state: "ND",
    stop_short_name: "Williston",
  },
  {
    stop_id: "WTS",
    state: "",
    stop_short_name: "Willits Calif Western Railroad Depot",
  },
  {
    stop_id: "WWD",
    state: "",
    stop_short_name: "Wildwood",
  },
  {
    stop_id: "YAZ",
    state: "MS",
    stop_short_name: "Yazoo City",
  },
  {
    stop_id: "YEM",
    state: "SC",
    stop_short_name: "Yemassee",
  },
  {
    stop_id: "YNY",
    state: "NY",
    stop_short_name: "Yonkers",
  },
  {
    stop_id: "YUM",
    state: "AZ",
    stop_short_name: "Yuma",
  },
];
export const routeList = [
  {
    "url_slug": "cascades",
    "label": "Amtrak Cascades",
    "routes": [60, 36924],
    "stoptimes": [
      { "stop_id": "EUG" },
      { "stop_id": "ALY" },
      { "stop_id": "SLM" },
      { "stop_id": "ORC" },
      { "stop_id": "PDX" },
      { "stop_id": "VAN" },
      { "stop_id": "KEL" },
      { "stop_id": "CTL" },
      { "stop_id": "OLW" },
      { "stop_id": "TAC" },
      { "stop_id": "TUK" },
      { "stop_id": "SEA" },
      { "stop_id": "EDM" },
      { "stop_id": "EVR" },
      { "stop_id": "STW" },
      { "stop_id": "MVW" },
      { "stop_id": "BEL" },
      { "stop_id": "VAC" }
    ],
  },
  {
    "url_slug": "capitol-corridor",
    "label": "Capitol Corridor",
    "routes": [84, 96, 36924],
    "stoptimes": [
      { "stop_id": "SJC" },
      { "stop_id": "SCC" },
      { "stop_id": "GAC" },
      { "stop_id": "FMT" },
      { "stop_id": "HAY" },
      { "stop_id": "OAC" },
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "BKY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "SUI" },
      { "stop_id": "FFV" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "RSV" },
      { "stop_id": "RLN" },
      { "stop_id": "ARN" }
    ],
  },
  {
    "url_slug": "san-joaquins",
    "label": "San Joaquins",
    "routes": [26025],
    "stoptimes": [
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "ACA" },
      { "stop_id": "SKN" },
      { "stop_id": "SAC" },
      { "stop_id": "LOD" },
      { "stop_id": "SKT" },
      { "stop_id": "MOD" },
      { "stop_id": "TRK" },
      { "stop_id": "MCD" },
      { "stop_id": "MDR" },
      { "stop_id": "FNO" },
      { "stop_id": "HNF" },
      { "stop_id": "COC" },
      { "stop_id": "WAC" },
      { "stop_id": "BFD" }
    ],
  },
  {
    "url_slug": "pacific-surfliner",
    "label": "Pacific Surfliner",
    "routes": [78, 36924],
    "stoptimes": [
      { "stop_id": "SAN" },
      { "stop_id": "OLT" },
      { "stop_id": "SOL" },
      { "stop_id": "OSD" },
      { "stop_id": "SNP" },
      { "stop_id": "SNC" },
      { "stop_id": "IRV" },
      { "stop_id": "SNA" },
      { "stop_id": "ANA" },
      { "stop_id": "FUL" },
      { "stop_id": "LAX" },
      { "stop_id": "GDL" },
      { "stop_id": "BUR" },
      { "stop_id": "VNC" },
      { "stop_id": "CWT" },
      { "stop_id": "SIM" },
      { "stop_id": "MPK" },
      { "stop_id": "CML" },
      { "stop_id": "OXN" },
      { "stop_id": "VEC" },
      { "stop_id": "CPN" },
      { "stop_id": "SBA" },
      { "stop_id": "GTA" },
      { "stop_id": "LPS" },
      { "stop_id": "GUA" },
      { "stop_id": "GVB" },
      { "stop_id": "SLO" }
    ],
  },
  {
    "url_slug": "heartland-flyer",
    "label": "Heartland Flyer",
    "routes": [86],
    "stoptimes": [
      { "stop_id": "FTW" },
      { "stop_id": "GLE" },
      { "stop_id": "ADM" },
      { "stop_id": "PVL" },
      { "stop_id": "PUR" },
      { "stop_id": "NOR" },
      { "stop_id": "OKC" }
    ],
  },
  {
    "url_slug": "hiawatha",
    "label": "Hiawatha Service",
    "routes": [54],
    "stoptimes": [
      { "stop_id": "MKE" },
      { "stop_id": "MKA" },
      { "stop_id": "SVT" },
      { "stop_id": "GLN" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "illinois-zephyr",
    "label": "Illinois Zephyr/Carl Sandburg",
    "routes": [51, 72, 93, 96],
    "stoptimes": [
      { "stop_id": "QCY" },
      { "stop_id": "MAC" },
      { "stop_id": "GBB" },
      { "stop_id": "KEE" },
      { "stop_id": "PCT" },
      { "stop_id": "MDT" },
      { "stop_id": "PLO" },
      { "stop_id": "NPV" },
      { "stop_id": "LAG" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "lincoln-service-missouri",
    "label": "Lincoln Service/Missouri River Runner",
    "routes": [51, 87, 36926, 36948, 42947],
    "stoptimes": [
      { "stop_id": "KCY" },
      { "stop_id": "IDP" },
      { "stop_id": "LEE" },
      { "stop_id": "WAR" },
      { "stop_id": "SED" },
      { "stop_id": "JEF" },
      { "stop_id": "HEM" },
      { "stop_id": "WAH" },
      { "stop_id": "KWD" },
      { "stop_id": "STL" },
      { "stop_id": "ALN" },
      { "stop_id": "CRV" },
      { "stop_id": "SPI" },
      { "stop_id": "LCN" },
      { "stop_id": "BNL" },
      { "stop_id": "PON" },
      { "stop_id": "DWT" },
      { "stop_id": "JOL" },
      { "stop_id": "SMT" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "illini",
    "label": "Illini/Saluki",
    "routes": [56, 62, 63],
    "stoptimes": [
      { "stop_id": "CDL" },
      { "stop_id": "DQN" },
      { "stop_id": "CEN" },
      { "stop_id": "EFG" },
      { "stop_id": "MAT" },
      { "stop_id": "CHM" },
      { "stop_id": "RTL" },
      { "stop_id": "GLM" },
      { "stop_id": "KKI" },
      { "stop_id": "HMW" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "wolverine-blue-water",
    "label": "Wolverine/Blue Water",
    "routes": [71, 80],
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "HMI" },
      { "stop_id": "NBU" },
      { "stop_id": "NLS" },
      { "stop_id": "DOA" },
      { "stop_id": "KAL" },
      { "stop_id": "BTL" },
      { "stop_id": "ALI" },
      { "stop_id": "JXN" },
      { "stop_id": "LNS" },
      { "stop_id": "ARB" },
      { "stop_id": "DER" },
      { "stop_id": "DET" },
      { "stop_id": "ROY" },
      { "stop_id": "TRM" },
      { "stop_id": "PNT" },
      { "stop_id": "DRD" },
      { "stop_id": "FLN" },
      { "stop_id": "LPE" },
      { "stop_id": "PTH" }
    ],
  },
  {
    "url_slug": "pere-marquette",
    "label": "Pere Marquette",
    "routes": [55],
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "SJM" },
      { "stop_id": "BAM" },
      { "stop_id": "HOM" },
      { "stop_id": "GRR" }
    ],
  },
  {
    "url_slug": "northeast-regional",
    "label": "Northeast Regional (all stations)",
    "routes": [88],
    "stoptimes": [
      { "stop_id": "RNK" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "NFK" },
      { "stop_id": "NPN" },
      { "stop_id": "WBG" },
      { "stop_id": "PTB" },
      { "stop_id": "RVM" },
      { "stop_id": "RVR" },
      { "stop_id": "ASD" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "WDB" },
      { "stop_id": "MSS" },
      { "stop_id": "BCV" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "OSB" },
      { "stop_id": "NLC" },
      { "stop_id": "MYS" },
      { "stop_id": "WLY" },
      { "stop_id": "KIN" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ],
  },
  {
    "url_slug": "northeast-regional-rvm-bos",
    "label": "Northeast Regional (Richmond-Boston)",
    "routes": [69, 70, 85, 91, 88],
    "stoptimes": [
      { "stop_id": "NFK" },
      { "stop_id": "NPN" },
      { "stop_id": "WBG" },
      { "stop_id": "PTB" },
      { "stop_id": "RVM" },
      { "stop_id": "RVR" },
      { "stop_id": "ASD" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "WDB" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "OSB" },
      { "stop_id": "NLC" },
      { "stop_id": "MYS" },
      { "stop_id": "WLY" },
      { "stop_id": "KIN" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ],
  },
  {
    "url_slug": "northeast-regional-rnk-bos",
    "label": "Northeast Regional (Roanoke-Boston)",
    "routes": [88, 36923],
    "stoptimes": [
      { "stop_id": "RNK" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "BCV" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "OSB" },
      { "stop_id": "NLC" },
      { "stop_id": "MYS" },
      { "stop_id": "WLY" },
      { "stop_id": "KIN" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ],
  },
  {
    "url_slug": "northeast-regional-rvm-spg",
    "label": "Northeast Regional (Richmond-Springfield)",
    "routes": [69, 70, 85, 91, 88, 90, 41042, 41044],
    "stoptimes": [
      { "stop_id": "NFK" },
      { "stop_id": "NPN" },
      { "stop_id": "WBG" },
      { "stop_id": "PTB" },
      { "stop_id": "RVM" },
      { "stop_id": "RVR" },
      { "stop_id": "ASD" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "WDB" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" }
    ],
  },
  {
    "url_slug": "northeast-regional-rnk-spg",
    "label": "Northeast Regional (Roanoke-Springfield)",
    "routes": [88, 90, 36923, 41042, 41044],
    "stoptimes": [
      { "stop_id": "RNK" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "BCV" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" }
    ],
  },
  {
    "url_slug": "acela",
    "label": "Acela",
    "routes": [40751],
    "stoptimes": [
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "STM" },
      { "stop_id": "NHV" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ],
  },
  {
    "url_slug": "hartford-line-valley-flyer",
    "label": "Hartford Line/Valley Flyer",
    "routes": [88, 90, 41042, 41044],
    "stoptimes": [
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" }
    ],
  },
  {
    "url_slug": "vermonter",
    "label": "Vermonter",
    "routes": [90],
    "stoptimes": [
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "MDN" },
      { "stop_id": "HFD" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" },
      { "stop_id": "BRA" },
      { "stop_id": "BLF" },
      { "stop_id": "CLA" },
      { "stop_id": "WNM" },
      { "stop_id": "WRJ" },
      { "stop_id": "RPH" },
      { "stop_id": "MPR" },
      { "stop_id": "WAB" },
      { "stop_id": "ESX" },
      { "stop_id": "SAB" }
    ],
  },
  {
    "url_slug": "keystone-service",
    "label": "Keystone Service",
    "routes": [64, 94],
    "stoptimes": [
      { "stop_id": "HAR" },
      { "stop_id": "MID" },
      { "stop_id": "ELT" },
      { "stop_id": "MJY" },
      { "stop_id": "LNC" },
      { "stop_id": "PAR" },
      { "stop_id": "COT" },
      { "stop_id": "DOW" },
      { "stop_id": "EXT" },
      { "stop_id": "PAO" },
      { "stop_id": "ARD" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "CWH" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "pennsylvanian",
    "label": "Pennsylvanian",
    "routes": [64],
    "stoptimes": [
      { "stop_id": "PGH" },
      { "stop_id": "GNB" },
      { "stop_id": "LAB" },
      { "stop_id": "JST" },
      { "stop_id": "ALT" },
      { "stop_id": "TYR" },
      { "stop_id": "HGD" },
      { "stop_id": "LEW" },
      { "stop_id": "HAR" },
      { "stop_id": "ELT" },
      { "stop_id": "LNC" },
      { "stop_id": "EXT" },
      { "stop_id": "PAO" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "empire-service",
    "label": "Empire Service",
    "routes": [68, 81, 95, 36921, 36949, 42948],
    "stoptimes": [
      { "stop_id": "TWO" },
      { "stop_id": "NFS" },
      { "stop_id": "NFL" },
      { "stop_id": "BFX" },
      { "stop_id": "BUF" },
      { "stop_id": "ROC" },
      { "stop_id": "SYR" },
      { "stop_id": "ROM" },
      { "stop_id": "UCA" },
      { "stop_id": "AMS" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "maple-leaf",
    "label": "Maple Leaf",
    "routes": [68],
    "stoptimes": [
      { "stop_id": "TWO" },
      { "stop_id": "NFS" },
      { "stop_id": "NFL" },
      { "stop_id": "BFX" },
      { "stop_id": "BUF" },
      { "stop_id": "ROC" },
      { "stop_id": "SYR" },
      { "stop_id": "ROM" },
      { "stop_id": "UCA" },
      { "stop_id": "AMS" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "adirondack-ethan-allen",
    "label": "Adirondack/Ethan Allen Express",
    "routes": [95, 36949],
    "stoptimes": [
      { "stop_id": "MTR" },
      { "stop_id": "SLQ" },
      { "stop_id": "RSP" },
      { "stop_id": "PLB" },
      // { "stop_id": "PRK" },
      { "stop_id": "BTN" },
      { "stop_id": "WSP" },
      { "stop_id": "POH" },
      { "stop_id": "VRN" },
      { "stop_id": "MBY" },
      { "stop_id": "FTC" },
      { "stop_id": "RUD" },
      { "stop_id": "CNV" },
      { "stop_id": "WHL" },
      { "stop_id": "FED" },
      { "stop_id": "SAR" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "berkshire-flyer",
    "label": "Berkshire Flyer",
    "routes": [42948],
    "stoptimes": [
      { "stop_id": "PIT" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "downeaster",
    "label": "Downeaster",
    "routes": [61],
    "stoptimes": [
      { "stop_id": "BON" },
      { "stop_id": "WOB" },
      { "stop_id": "HHL" },
      { "stop_id": "EXR" },
      { "stop_id": "DHM" },
      { "stop_id": "DOV" },
      { "stop_id": "WEM" },
      { "stop_id": "SAO" },
      { "stop_id": "ORB" },
      { "stop_id": "POR" },
      { "stop_id": "FRE" },
      { "stop_id": "BRK" }
    ],
  },
  {
    "url_slug": "carolinian-piedmont",
    "label": "Carolinian/Piedmont",
    "routes": [79, 85],
    "stoptimes": [
      { "stop_id": "CLT" },
      { "stop_id": "KAN" },
      { "stop_id": "SAL" },
      { "stop_id": "HPT" },
      { "stop_id": "GRO" },
      { "stop_id": "BNC" },
      { "stop_id": "DNC" },
      { "stop_id": "CYN" },
      { "stop_id": "RGH" },
      { "stop_id": "SSM" },
      { "stop_id": "WLN" },
      { "stop_id": "RMT" },
      { "stop_id": "PTB" },
      { "stop_id": "RVR" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "coast-starlight",
    "label": "Coast Starlight",
    "routes": [36924],
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "BUR" },
      { "stop_id": "VNC" },
      { "stop_id": "SIM" },
      { "stop_id": "OXN" },
      { "stop_id": "SBA" },
      { "stop_id": "SLO" },
      { "stop_id": "PRB" },
      { "stop_id": "SNS" },
      { "stop_id": "SJC" },
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "MTZ" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "CIC" },
      { "stop_id": "RDD" },
      { "stop_id": "DUN" },
      { "stop_id": "KFS" },
      { "stop_id": "CMO" },
      { "stop_id": "EUG" },
      { "stop_id": "ALY" },
      { "stop_id": "SLM" },
      { "stop_id": "PDX" },
      { "stop_id": "VAN" },
      { "stop_id": "KEL" },
      { "stop_id": "CTL" },
      { "stop_id": "OLW" },
      { "stop_id": "TAC" },
      { "stop_id": "SEA" }
    ],
  },
  {
    "url_slug": "empire-builder",
    "label": "Empire Builder",
    "routes": [75],
    "stoptimes": [
      { "stop_id": "SEA" },
      { "stop_id": "EDM" },
      { "stop_id": "EVR" },
      { "stop_id": "LWA" },
      { "stop_id": "WEN" },
      { "stop_id": "EPH" },
      { "stop_id": "PDX" },
      { "stop_id": "VAN" },
      { "stop_id": "BNG" },
      { "stop_id": "WIH" },
      { "stop_id": "PSC" },
      { "stop_id": "SPK" },
      { "stop_id": "SPT" },
      { "stop_id": "LIB" },
      { "stop_id": "WFH" },
      { "stop_id": "WGL" },
      { "stop_id": "ESM" },
      { "stop_id": "GPK" },
      { "stop_id": "BRO" },
      { "stop_id": "CUT" },
      { "stop_id": "SBY" },
      { "stop_id": "HAV" },
      { "stop_id": "MAL" },
      { "stop_id": "GGW" },
      { "stop_id": "WPT" },
      { "stop_id": "WTN" },
      { "stop_id": "STN" },
      { "stop_id": "MOT" },
      { "stop_id": "RUG" },
      { "stop_id": "DVL" },
      { "stop_id": "GFK" },
      { "stop_id": "FAR" },
      { "stop_id": "DLK" },
      { "stop_id": "SPL" },
      { "stop_id": "SCD" },
      { "stop_id": "MSP" },
      { "stop_id": "RDW" },
      { "stop_id": "WIN" },
      { "stop_id": "LSE" },
      { "stop_id": "TOH" },
      { "stop_id": "WDL" },
      { "stop_id": "POG" },
      { "stop_id": "CBS" },
      { "stop_id": "MKE" },
      { "stop_id": "GLN" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "california-zephyr",
    "label": "California Zephyr",
    "routes": [96],
    "stoptimes": [
      { "stop_id": "EMY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "RSV" },
      { "stop_id": "COX" },
      { "stop_id": "TRU" },
      { "stop_id": "RNO" },
      { "stop_id": "WNN" },
      { "stop_id": "ELK" },
      { "stop_id": "SLC" },
      { "stop_id": "PRO" },
      { "stop_id": "HER" },
      { "stop_id": "GRI" },
      { "stop_id": "GJT" },
      { "stop_id": "GSC" },
      { "stop_id": "GRA" },
      { "stop_id": "WIP" },
      { "stop_id": "DEN" },
      { "stop_id": "FMG" },
      { "stop_id": "MCK" },
      { "stop_id": "HLD" },
      { "stop_id": "HAS" },
      { "stop_id": "LNK" },
      { "stop_id": "OMA" },
      { "stop_id": "CRN" },
      { "stop_id": "OSC" },
      { "stop_id": "OTM" },
      { "stop_id": "MTP" },
      { "stop_id": "BRL" },
      { "stop_id": "GBB" },
      { "stop_id": "PCT" },
      { "stop_id": "NPV" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "southwest-chief",
    "label": "Southwest Chief",
    "routes": [51],
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "FUL" },
      { "stop_id": "RIV" },
      { "stop_id": "SNB" },
      { "stop_id": "VRV" },
      { "stop_id": "BAR" },
      { "stop_id": "NDL" },
      { "stop_id": "KNG" },
      { "stop_id": "FLG" },
      { "stop_id": "WLO" },
      { "stop_id": "GLP" },
      { "stop_id": "ABQ" },
      { "stop_id": "LMY" },
      { "stop_id": "LSV" },
      { "stop_id": "RAT" },
      { "stop_id": "TRI" },
      { "stop_id": "LAJ" },
      { "stop_id": "LMR" },
      { "stop_id": "GCK" },
      { "stop_id": "DDG" },
      { "stop_id": "HUT" },
      { "stop_id": "NEW" },
      { "stop_id": "TOP" },
      { "stop_id": "LRC" },
      { "stop_id": "KCY" },
      { "stop_id": "LAP" },
      { "stop_id": "FMD" },
      { "stop_id": "GBB" },
      { "stop_id": "PCT" },
      { "stop_id": "MDT" },
      { "stop_id": "NPV" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "texas-eagle-sunset-limited",
    "label": "Texas Eagle/Sunset Limited",
    "routes": [87, 36930],
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "POS" },
      { "stop_id": "ONA" },
      { "stop_id": "PSN" },
      { "stop_id": "YUM" },
      { "stop_id": "MRC" },
      { "stop_id": "TUS" },
      { "stop_id": "BEN" },
      { "stop_id": "LDB" },
      { "stop_id": "DEM" },
      { "stop_id": "ELP" },
      { "stop_id": "ALP" },
      { "stop_id": "SND" },
      { "stop_id": "DRT" },
      { "stop_id": "SAS" },
      { "stop_id": "HOS" },
      { "stop_id": "BMT" },
      { "stop_id": "LCH" },
      { "stop_id": "LFT" },
      { "stop_id": "NIB" },
      { "stop_id": "SCH" },
      { "stop_id": "NOL" },
      { "stop_id": "SMC" },
      { "stop_id": "AUS" },
      { "stop_id": "TAY" },
      { "stop_id": "TPL" },
      { "stop_id": "MCG" },
      { "stop_id": "CBR" },
      { "stop_id": "FTW" },
      { "stop_id": "DAL" },
      { "stop_id": "MIN" },
      { "stop_id": "LVW" },
      { "stop_id": "MHL" },
      { "stop_id": "TXA" },
      { "stop_id": "HOP" },
      { "stop_id": "ARK" },
      { "stop_id": "MVN" },
      { "stop_id": "LRK" },
      { "stop_id": "WNR" },
      { "stop_id": "PBF" },
      { "stop_id": "ACD" },
      { "stop_id": "STL" },
      { "stop_id": "ALN" },
      { "stop_id": "CRV" },
      { "stop_id": "SPI" },
      { "stop_id": "LCN" },
      { "stop_id": "BNL" },
      { "stop_id": "PON" },
      { "stop_id": "JOL" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "city-of-new-orleans",
    "label": "City of New Orleans",
    "routes": [62],
    "stoptimes": [
      { "stop_id": "NOL" },
      { "stop_id": "HMD" },
      { "stop_id": "MCB" },
      { "stop_id": "BRH" },
      { "stop_id": "HAZ" },
      { "stop_id": "JAN" },
      { "stop_id": "YAZ" },
      { "stop_id": "GWD" },
      { "stop_id": "MKS" },
      { "stop_id": "MEM" },
      { "stop_id": "NBN" },
      { "stop_id": "FTN" },
      { "stop_id": "CDL" },
      { "stop_id": "CEN" },
      { "stop_id": "EFG" },
      { "stop_id": "MAT" },
      { "stop_id": "CHM" },
      { "stop_id": "KKI" },
      { "stop_id": "HMW" },
      { "stop_id": "CHI" }
    ],
  },
  {
    "url_slug": "lake-shore-limited",
    "label": "Lake Shore Limited",
    "routes": [81],
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "SOB" },
      { "stop_id": "EKH" },
      { "stop_id": "WTI" },
      { "stop_id": "BYN" },
      { "stop_id": "TOL" },
      { "stop_id": "SKY" },
      { "stop_id": "ELY" },
      { "stop_id": "CLE" },
      { "stop_id": "ERI" },
      { "stop_id": "BUF" },
      { "stop_id": "ROC" },
      { "stop_id": "SYR" },
      { "stop_id": "UCA" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "NYP" },
      { "stop_id": "PIT" },
      { "stop_id": "SPG" },
      { "stop_id": "WOR" },
      { "stop_id": "FRA" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" },
    ],
  },
  {
    "url_slug": "capitol-limited",
    "label": "Capitol Limited",
    "routes": [36922],
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "SOB" },
      { "stop_id": "EKH" },
      { "stop_id": "WTI" },
      { "stop_id": "TOL" },
      { "stop_id": "SKY" },
      { "stop_id": "ELY" },
      { "stop_id": "CLE" },
      { "stop_id": "ALC" },
      { "stop_id": "PGH" },
      { "stop_id": "COV" },
      { "stop_id": "CUM" },
      { "stop_id": "MRB" },
      { "stop_id": "HFY" },
      { "stop_id": "RKV" },
      { "stop_id": "WAS" }
    ],
  },
  {
    "url_slug": "silver",
    "label": "Atlantic Coast Service",
    "routes": [69, 70, 85, 91],
    "stoptimes": [
      { "stop_id": "MIA" },
      { "stop_id": "HOL" },
      { "stop_id": "FTL" },
      { "stop_id": "DFB" },
      { "stop_id": "DLB" },
      { "stop_id": "WPB" },
      { "stop_id": "OKE" },
      { "stop_id": "SBG" },
      { "stop_id": "WTH" },
      { "stop_id": "TPA" },
      { "stop_id": "LKL" },
      { "stop_id": "LAK" },
      { "stop_id": "KIS" },
      { "stop_id": "ORL" },
      { "stop_id": "WPK" },
      { "stop_id": "DLD" },
      { "stop_id": "PAK" },
      { "stop_id": "JAX" },
      { "stop_id": "JSP" },
      { "stop_id": "SAV" },
      { "stop_id": "DNK" },
      { "stop_id": "CLB" },
      { "stop_id": "CAM" },
      { "stop_id": "YEM" },
      { "stop_id": "CHS" },
      { "stop_id": "KTR" },
      { "stop_id": "FLO" },
      { "stop_id": "DIL" },
      { "stop_id": "FAY" },
      { "stop_id": "HAM" },
      { "stop_id": "SOP" },
      { "stop_id": "CYN" },
      { "stop_id": "RGH" },
      { "stop_id": "SSM" },
      { "stop_id": "WLN" },
      { "stop_id": "RMT" },
      { "stop_id": "PTB" },
      { "stop_id": "RVR" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "crescent",
    "label": "Crescent",
    "routes": [36923],
    "stoptimes": [
      { "stop_id": "NOL" },
      { "stop_id": "SDL" },
      { "stop_id": "PIC" },
      { "stop_id": "HBG" },
      { "stop_id": "LAU" },
      { "stop_id": "MEI" },
      { "stop_id": "TCL" },
      { "stop_id": "BHM" },
      { "stop_id": "ATN" },
      { "stop_id": "ATL" },
      { "stop_id": "GNS" },
      { "stop_id": "TCA" },
      { "stop_id": "CSN" },
      { "stop_id": "GRV" },
      { "stop_id": "SPB" },
      { "stop_id": "GAS" },
      { "stop_id": "CLT" },
      { "stop_id": "SAL" },
      { "stop_id": "HPT" },
      { "stop_id": "GRO" },
      { "stop_id": "DAN" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "cardinal",
    "label": "Cardinal",
    "routes": [58],
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "DYE" },
      { "stop_id": "REN" },
      { "stop_id": "LAF" },
      { "stop_id": "CRF" },
      { "stop_id": "IND" },
      { "stop_id": "COI" },
      { "stop_id": "CIN" },
      { "stop_id": "MAY" },
      { "stop_id": "SPM" },
      { "stop_id": "AKY" },
      { "stop_id": "HUN" },
      { "stop_id": "CHW" },
      { "stop_id": "MNG" },
      { "stop_id": "THN" },
      { "stop_id": "PRC" },
      { "stop_id": "HIN" },
      { "stop_id": "ALD" },
      { "stop_id": "WSS" },
      { "stop_id": "CLF" },
      { "stop_id": "STA" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ],
  },
  {
    "url_slug": "auto-train",
    "label": "Auto Train",
    "routes": [77],
    "stoptimes": [
      { "stop_id": "SFA" },
      { "stop_id": "LOR" }
    ],
  },
];
