export const routeList = [
  {
    "url_slug": "cascades",
    "label": "Amtrak Cascades",
    "routes": [60, 36924],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "EUG" },
      { "stop_id": "ALY" },
      { "stop_id": "SLM" },
      { "stop_id": "ORC" },
      { "stop_id": "PDX" },
      { "stop_id": "VAN" },
      { "stop_id": "KEL" },
      { "stop_id": "CTL" },
      { "stop_id": "OLW" },
      { "stop_id": "TAC" },
      { "stop_id": "TUK" },
      { "stop_id": "SEA" },
      { "stop_id": "EDM" },
      { "stop_id": "EVR" },
      { "stop_id": "STW" },
      { "stop_id": "MVW" },
      { "stop_id": "BEL" },
      { "stop_id": "VAC" }
    ]
  },
  {
    "url_slug": "capitol-corridor",
    "label": "Capitol Corridor",
    "routes": [84, 96, 36924],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "SJC" },
      { "stop_id": "SCC" },
      { "stop_id": "GAC" },
      { "stop_id": "FMT" },
      { "stop_id": "HAY" },
      { "stop_id": "OAC" },
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "BKY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "SUI" },
      { "stop_id": "FFV" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "RSV" },
      { "stop_id": "RLN" },
      { "stop_id": "ARN" }
    ]
  },
  {
    "url_slug": "san-joaquins",
    "label": "San Joaquins",
    "routes": [26025],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "ACA" },
      { "stop_id": "SKN" },
      { "stop_id": "SAC" },
      { "stop_id": "LOD" },
      { "stop_id": "SKT" },
      { "stop_id": "MOD" },
      { "stop_id": "TRK" },
      { "stop_id": "MCD" },
      { "stop_id": "MDR" },
      { "stop_id": "FNO" },
      { "stop_id": "HNF" },
      { "stop_id": "COC" },
      { "stop_id": "WAC" },
      { "stop_id": "BFD" }
    ]
  },
  {
    "url_slug": "pacific-surfliner",
    "label": "Pacific Surfliner",
    "routes": [78, 36924],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "SAN" },
      { "stop_id": "OLT" },
      { "stop_id": "SOL" },
      { "stop_id": "OSD" },
      { "stop_id": "SNP" },
      { "stop_id": "SNC" },
      { "stop_id": "IRV" },
      { "stop_id": "SNA" },
      { "stop_id": "ANA" },
      { "stop_id": "FUL" },
      { "stop_id": "LAX" },
      { "stop_id": "GDL" },
      { "stop_id": "BUR" },
      { "stop_id": "VNC" },
      { "stop_id": "CWT" },
      { "stop_id": "SIM" },
      { "stop_id": "MPK" },
      { "stop_id": "CML" },
      { "stop_id": "OXN" },
      { "stop_id": "VEC" },
      { "stop_id": "CPN" },
      { "stop_id": "SBA" },
      { "stop_id": "GTA" },
      { "stop_id": "LPS" },
      { "stop_id": "GUA" },
      { "stop_id": "GVB" },
      { "stop_id": "SLO" }
    ]
  },
  {
    "url_slug": "coast-starlight",
    "label": "Coast Starlight",
    "routes": [36924],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "BUR" },
      { "stop_id": "VNC" },
      { "stop_id": "SIM" },
      { "stop_id": "OXN" },
      { "stop_id": "SBA" },
      { "stop_id": "SLO" },
      { "stop_id": "PRB" },
      { "stop_id": "SNS" },
      { "stop_id": "SJC" },
      { "stop_id": "OKJ" },
      { "stop_id": "EMY" },
      { "stop_id": "MTZ" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "CIC" },
      { "stop_id": "RDD" },
      { "stop_id": "DUN" },
      { "stop_id": "KFS" },
      { "stop_id": "CMO" },
      { "stop_id": "EUG" },
      { "stop_id": "ALY" },
      { "stop_id": "SLM" },
      { "stop_id": "PDX" },
      { "stop_id": "VAN" },
      { "stop_id": "KEL" },
      { "stop_id": "CTL" },
      { "stop_id": "OLW" },
      { "stop_id": "TAC" },
      { "stop_id": "SEA" }
    ]
  },
  {
    "url_slug": "empire-builder",
    "label": "Empire Builder",
    "routes": [75],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "SEA" },
      { "stop_id": "EDM" },
      { "stop_id": "EVR" },
      { "stop_id": "LWA" },
      { "stop_id": "WEN" },
      { "stop_id": "EPH" },
      { "stop_id": "SPK" },
      { "stop_id": "PSC" },
      { "stop_id": "WIH" },
      { "stop_id": "BNG" },
      { "stop_id": "VAN" },
      { "stop_id": "PDX" },
      { "stop_id": "SPT" },
      { "stop_id": "LIB" },
      { "stop_id": "WFH" },
      { "stop_id": "WGL" },
      { "stop_id": "ESM" },
      { "stop_id": "GPK" },
      { "stop_id": "BRO" },
      { "stop_id": "CUT" },
      { "stop_id": "SBY" },
      { "stop_id": "HAV" },
      { "stop_id": "MAL" },
      { "stop_id": "GGW" },
      { "stop_id": "WPT" },
      { "stop_id": "WTN" },
      { "stop_id": "STN" },
      { "stop_id": "MOT" },
      { "stop_id": "RUG" },
      { "stop_id": "DVL" },
      { "stop_id": "GFK" },
      { "stop_id": "FAR" },
      { "stop_id": "DLK" },
      { "stop_id": "SPL" },
      { "stop_id": "SCD" },
      { "stop_id": "MSP" },
      { "stop_id": "RDW" },
      { "stop_id": "WIN" },
      { "stop_id": "LSE" },
      { "stop_id": "TOH" },
      { "stop_id": "WDL" },
      { "stop_id": "POG" },
      { "stop_id": "CBS" },
      { "stop_id": "MKE" },
      { "stop_id": "GLN" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "california-zephyr",
    "label": "California Zephyr",
    "routes": [96],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "EMY" },
      { "stop_id": "RIC" },
      { "stop_id": "MTZ" },
      { "stop_id": "DAV" },
      { "stop_id": "SAC" },
      { "stop_id": "RSV" },
      { "stop_id": "COX" },
      { "stop_id": "TRU" },
      { "stop_id": "RNO" },
      { "stop_id": "WNN" },
      { "stop_id": "ELK" },
      { "stop_id": "SLC" },
      { "stop_id": "PRO" },
      { "stop_id": "HER" },
      { "stop_id": "GRI" },
      { "stop_id": "GJT" },
      { "stop_id": "GSC" },
      { "stop_id": "GRA" },
      { "stop_id": "WIP" },
      { "stop_id": "DEN" },
      { "stop_id": "FMG" },
      { "stop_id": "MCK" },
      { "stop_id": "HLD" },
      { "stop_id": "HAS" },
      { "stop_id": "LNK" },
      { "stop_id": "OMA" },
      { "stop_id": "CRN" },
      { "stop_id": "OSC" },
      { "stop_id": "OTM" },
      { "stop_id": "MTP" },
      { "stop_id": "BRL" },
      { "stop_id": "GBB" },
      { "stop_id": "PCT" },
      { "stop_id": "NPV" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "southwest-chief",
    "label": "Southwest Chief",
    "routes": [51],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "FUL" },
      { "stop_id": "RIV" },
      { "stop_id": "SNB" },
      { "stop_id": "VRV" },
      { "stop_id": "BAR" },
      { "stop_id": "NDL" },
      { "stop_id": "KNG" },
      { "stop_id": "FLG" },
      { "stop_id": "WLO" },
      { "stop_id": "GLP" },
      { "stop_id": "ABQ" },
      { "stop_id": "LMY" },
      { "stop_id": "LSV" },
      { "stop_id": "RAT" },
      { "stop_id": "TRI" },
      { "stop_id": "LAJ" },
      { "stop_id": "LMR" },
      { "stop_id": "GCK" },
      { "stop_id": "DDG" },
      { "stop_id": "HUT" },
      { "stop_id": "NEW" },
      { "stop_id": "TOP" },
      { "stop_id": "LRC" },
      { "stop_id": "KCY" },
      { "stop_id": "LAP" },
      { "stop_id": "FMD" },
      { "stop_id": "GBB" },
      { "stop_id": "PCT" },
      { "stop_id": "MDT" },
      { "stop_id": "NPV" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "texas-eagle-sunset-limited",
    "label": "Texas Eagle/Sunset Limited",
    "routes": [87, 36930],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "LAX" },
      { "stop_id": "POS" },
      { "stop_id": "ONA" },
      { "stop_id": "PSN" },
      { "stop_id": "YUM" },
      { "stop_id": "MRC" },
      { "stop_id": "TUS" },
      { "stop_id": "BEN" },
      { "stop_id": "LDB" },
      { "stop_id": "DEM" },
      { "stop_id": "ELP" },
      { "stop_id": "ALP" },
      { "stop_id": "SND" },
      { "stop_id": "DRT" },
      { "stop_id": "NOL" },
      { "stop_id": "SCH" },
      { "stop_id": "NIB" },
      { "stop_id": "LFT" },
      { "stop_id": "LCH" },
      { "stop_id": "BMT" },
      { "stop_id": "HOS" },
      { "stop_id": "SAS" },
      { "stop_id": "SMC" },
      { "stop_id": "AUS" },
      { "stop_id": "TAY" },
      { "stop_id": "TPL" },
      { "stop_id": "MCG" },
      { "stop_id": "CBR" },
      { "stop_id": "FTW" },
      { "stop_id": "DAL" },
      { "stop_id": "MIN" },
      { "stop_id": "LVW" },
      { "stop_id": "MHL" },
      { "stop_id": "TXA" },
      { "stop_id": "HOP" },
      { "stop_id": "ARK" },
      { "stop_id": "MVN" },
      { "stop_id": "LRK" },
      { "stop_id": "WNR" },
      { "stop_id": "PBF" },
      { "stop_id": "ACD" },
      { "stop_id": "STL" },
      { "stop_id": "ALN" },
      { "stop_id": "CRV" },
      { "stop_id": "SPI" },
      { "stop_id": "LCN" },
      { "stop_id": "BNL" },
      { "stop_id": "PON" },
      { "stop_id": "JOL" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "heartland-flyer",
    "label": "Heartland Flyer",
    "routes": [86],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "FTW" },
      { "stop_id": "GLE" },
      { "stop_id": "ADM" },
      { "stop_id": "PVL" },
      { "stop_id": "PUR" },
      { "stop_id": "NOR" },
      { "stop_id": "OKC" }
    ]
  },
  {
    "url_slug": "city-of-new-orleans",
    "label": "City of New Orleans",
    "routes": [62],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "NOL" },
      { "stop_id": "HMD" },
      { "stop_id": "MCB" },
      { "stop_id": "BRH" },
      { "stop_id": "HAZ" },
      { "stop_id": "JAN" },
      { "stop_id": "YAZ" },
      { "stop_id": "GWD" },
      { "stop_id": "MKS" },
      { "stop_id": "MEM" },
      { "stop_id": "NBN" },
      { "stop_id": "FTN" },
      { "stop_id": "CDL" },
      { "stop_id": "CEN" },
      { "stop_id": "EFG" },
      { "stop_id": "MAT" },
      { "stop_id": "CHM" },
      { "stop_id": "KKI" },
      { "stop_id": "HMW" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "illinois-zephyr",
    "label": "Illinois Zephyr/Carl Sandburg",
    "routes": [51, 72, 93, 96],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "QCY" },
      { "stop_id": "MAC" },
      { "stop_id": "GBB" },
      { "stop_id": "KEE" },
      { "stop_id": "PCT" },
      { "stop_id": "MDT" },
      { "stop_id": "PLO" },
      { "stop_id": "NPV" },
      { "stop_id": "LAG" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "lincoln-service-missouri",
    "label": "Lincoln Service/Missouri River Runner",
    "routes": [51, 87, 36926, 36948, 42947],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "KCY" },
      { "stop_id": "IDP" },
      { "stop_id": "LEE" },
      { "stop_id": "WAR" },
      { "stop_id": "SED" },
      { "stop_id": "JEF" },
      { "stop_id": "HEM" },
      { "stop_id": "WAH" },
      { "stop_id": "KWD" },
      { "stop_id": "STL" },
      { "stop_id": "ALN" },
      { "stop_id": "CRV" },
      { "stop_id": "SPI" },
      { "stop_id": "LCN" },
      { "stop_id": "BNL" },
      { "stop_id": "PON" },
      { "stop_id": "DWT" },
      { "stop_id": "JOL" },
      { "stop_id": "SMT" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "illini",
    "label": "Illini/Saluki",
    "routes": [56, 62, 63],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CDL" },
      { "stop_id": "DQN" },
      { "stop_id": "CEN" },
      { "stop_id": "EFG" },
      { "stop_id": "MAT" },
      { "stop_id": "CHM" },
      { "stop_id": "RTL" },
      { "stop_id": "GLM" },
      { "stop_id": "KKI" },
      { "stop_id": "HMW" },
      { "stop_id": "CHI" }
    ]
  },
  {
    "url_slug": "wolverine-blue-water",
    "label": "Wolverine/Blue Water",
    "routes": [71, 80],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "HMI" },
      { "stop_id": "NBU" },
      { "stop_id": "NLS" },
      { "stop_id": "DOA" },
      { "stop_id": "KAL" },
      { "stop_id": "BTL" },
      { "stop_id": "LNS" },
      { "stop_id": "DRD" },
      { "stop_id": "FLN" },
      { "stop_id": "LPE" },
      { "stop_id": "PTH" },
      { "stop_id": "ALI" },
      { "stop_id": "JXN" },
      { "stop_id": "ARB" },
      { "stop_id": "DER" },
      { "stop_id": "DET" },
      { "stop_id": "ROY" },
      { "stop_id": "TRM" },
      { "stop_id": "PNT" }
    ]
  },
  {
    "url_slug": "lake-shore-limited",
    "label": "Lake Shore Limited",
    "routes": [81, 36922],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "SOB" },
      { "stop_id": "EKH" },
      { "stop_id": "WTI" },
      { "stop_id": "BYN" },
      { "stop_id": "TOL" },
      { "stop_id": "SKY" },
      { "stop_id": "ELY" },
      { "stop_id": "CLE" },
      { "stop_id": "ERI" },
      { "stop_id": "BUF" },
      { "stop_id": "ROC" },
      { "stop_id": "SYR" },
      { "stop_id": "UCA" },
      { "stop_id": "SDY" },
      { "stop_id": "NYP" },
      { "stop_id": "CRT" },
      { "stop_id": "POU" },
      { "stop_id": "RHI" },
      { "stop_id": "ALB" },
      { "stop_id": "PIT" },
      { "stop_id": "SPG" },
      { "stop_id": "WOR" },
      { "stop_id": "FRA" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ]
  },
  {
    "url_slug": "capitol-limited",
    "label": "Capitol Limited",
    "routes": [81, 36922],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "SOB" },
      { "stop_id": "EKH" },
      { "stop_id": "WTI" },
      { "stop_id": "TOL" },
      { "stop_id": "SKY" },
      { "stop_id": "ELY" },
      { "stop_id": "CLE" },
      { "stop_id": "ALC" },
      { "stop_id": "PGH" },
      { "stop_id": "COV" },
      { "stop_id": "CUM" },
      { "stop_id": "MRB" },
      { "stop_id": "HFY" },
      { "stop_id": "RKV" },
      { "stop_id": "WAS" }
    ]
  },
  {
    "url_slug": "empire-service",
    "label": "Empire Service/Maple Leaf",
    "routes": [68, 81, 95, 36921, 36949, 42948],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "TWO" },
      { "stop_id": "NFS" },
      { "stop_id": "NFL" },
      { "stop_id": "BFX" },
      { "stop_id": "BUF" },
      { "stop_id": "ROC" },
      { "stop_id": "SYR" },
      { "stop_id": "ROM" },
      { "stop_id": "UCA" },
      { "stop_id": "AMS" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "northeast-regional",
    "label": "Northeast Regional",
    "routes": [88],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "RNK" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "BCV" },
      { "stop_id": "NFK" },
      { "stop_id": "PTB" },
      { "stop_id": "NPN" },
      { "stop_id": "WBG" },
      { "stop_id": "RVM" },
      { "stop_id": "RVR" },
      { "stop_id": "ASD" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "WDB" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "ABE" },
      { "stop_id": "NRK" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "NRO" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "OSB" },
      { "stop_id": "NLC" },
      { "stop_id": "MYS" },
      { "stop_id": "WLY" },
      { "stop_id": "KIN" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ]
  },
  {
    "url_slug": "acela",
    "label": "Acela",
    "routes": [40751],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "STM" },
      { "stop_id": "NHV" },
      { "stop_id": "PVD" },
      { "stop_id": "RTE" },
      { "stop_id": "BBY" },
      { "stop_id": "BOS" }
    ]
  },
  {
    "url_slug": "hartford-line-valley-flyer",
    "label": "Hartford Line/Valley Flyer",
    "routes": [88, 90, 41042, 41044],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "NHV" },
      { "stop_id": "STS" },
      { "stop_id": "WFD" },
      { "stop_id": "MDN" },
      { "stop_id": "BER" },
      { "stop_id": "HFD" },
      { "stop_id": "WND" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" }
    ]
  },
  {
    "url_slug": "keystone-pennsylvanian",
    "label": "Keystone/Pennsylvanian",
    "routes": [64, 94],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "PGH" },
      { "stop_id": "GNB" },
      { "stop_id": "LAB" },
      { "stop_id": "JST" },
      { "stop_id": "ALT" },
      { "stop_id": "TYR" },
      { "stop_id": "HGD" },
      { "stop_id": "LEW" },
      { "stop_id": "HAR" },
      { "stop_id": "MID" },
      { "stop_id": "ELT" },
      { "stop_id": "MJY" },
      { "stop_id": "LNC" },
      { "stop_id": "PAR" },
      { "stop_id": "COT" },
      { "stop_id": "DOW" },
      { "stop_id": "EXT" },
      { "stop_id": "PAO" },
      { "stop_id": "ARD" },
      { "stop_id": "PHL" },
      { "stop_id": "PHN" },
      { "stop_id": "CWH" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "EWR" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "adirondack-ethan-allen",
    "label": "Adirondack/Ethan Allen Express",
    "routes": [68, 81, 95, 36921, 36949, 42948],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "MTR" },
      { "stop_id": "SLQ" },
      { "stop_id": "RSP" },
      { "stop_id": "PLB" },
      // { "stop_id": "PRK" },
      { "stop_id": "WSP" },
      { "stop_id": "POH" },
      { "stop_id": "FTC" },
      { "stop_id": "WHL" },
      { "stop_id": "BTN" },
      { "stop_id": "VRN" },
      { "stop_id": "MBY" },
      { "stop_id": "RUD" },
      { "stop_id": "CNV" },
      { "stop_id": "FED" },
      { "stop_id": "SAR" },
      { "stop_id": "SDY" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "berkshire-flyer",
    "label": "Berkshire Flyer",
    "routes": [42948],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "PIT" },
      { "stop_id": "ALB" },
      { "stop_id": "HUD" },
      { "stop_id": "RHI" },
      { "stop_id": "POU" },
      { "stop_id": "CRT" },
      { "stop_id": "YNY" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "vermonter",
    "label": "Vermonter",
    "routes": [90],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "WAS" },
      { "stop_id": "NCR" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" },
      { "stop_id": "STM" },
      { "stop_id": "BRP" },
      { "stop_id": "NHV" },
      { "stop_id": "MDN" },
      { "stop_id": "HFD" },
      { "stop_id": "WNL" },
      { "stop_id": "SPG" },
      { "stop_id": "HLK" },
      { "stop_id": "NHT" },
      { "stop_id": "GFD" },
      { "stop_id": "BRA" },
      { "stop_id": "BLF" },
      { "stop_id": "CLA" },
      { "stop_id": "WNM" },
      { "stop_id": "WRJ" },
      { "stop_id": "RPH" },
      { "stop_id": "MPR" },
      { "stop_id": "WAB" },
      { "stop_id": "ESX" },
      { "stop_id": "SAB" }
    ]
  },
  {
    "url_slug": "crescent",
    "label": "Crescent",
    "routes": [36923],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "NOL" },
      { "stop_id": "SDL" },
      { "stop_id": "PIC" },
      { "stop_id": "HBG" },
      { "stop_id": "LAU" },
      { "stop_id": "MEI" },
      { "stop_id": "TCL" },
      { "stop_id": "BHM" },
      { "stop_id": "ATN" },
      { "stop_id": "ATL" },
      { "stop_id": "GNS" },
      { "stop_id": "TCA" },
      { "stop_id": "CSN" },
      { "stop_id": "GRV" },
      { "stop_id": "SPB" },
      { "stop_id": "GAS" },
      { "stop_id": "CLT" },
      { "stop_id": "SAL" },
      { "stop_id": "HPT" },
      { "stop_id": "GRO" },
      { "stop_id": "DAN" },
      { "stop_id": "LYH" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "cardinal",
    "label": "Cardinal",
    "routes": [58],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CHI" },
      { "stop_id": "DYE" },
      { "stop_id": "REN" },
      { "stop_id": "LAF" },
      { "stop_id": "CRF" },
      { "stop_id": "IND" },
      { "stop_id": "COI" },
      { "stop_id": "CIN" },
      { "stop_id": "MAY" },
      { "stop_id": "SPM" },
      { "stop_id": "AKY" },
      { "stop_id": "HUN" },
      { "stop_id": "CHW" },
      { "stop_id": "MNG" },
      { "stop_id": "THN" },
      { "stop_id": "PRC" },
      { "stop_id": "HIN" },
      { "stop_id": "ALD" },
      { "stop_id": "WSS" },
      { "stop_id": "CLF" },
      { "stop_id": "STA" },
      { "stop_id": "CVS" },
      { "stop_id": "CLP" },
      { "stop_id": "MSS" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "downeaster",
    "label": "Downeaster",
    "routes": [61],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "BON" },
      { "stop_id": "WOB" },
      { "stop_id": "HHL" },
      { "stop_id": "EXR" },
      { "stop_id": "DHM" },
      { "stop_id": "DOV" },
      { "stop_id": "WEM" },
      { "stop_id": "SAO" },
      { "stop_id": "ORB" },
      { "stop_id": "POR" },
      { "stop_id": "FRE" },
      { "stop_id": "BRK" }
    ]
  },
  {
    "url_slug": "silver",
    "label": "Atlantic Coast Service",
    "routes": [69, 70, 85, 91],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "MIA" },
      { "stop_id": "HOL" },
      { "stop_id": "FTL" },
      { "stop_id": "DFB" },
      { "stop_id": "DLB" },
      { "stop_id": "WPB" },
      { "stop_id": "OKE" },
      { "stop_id": "SBG" },
      { "stop_id": "WTH" },
      { "stop_id": "LKL" },
      { "stop_id": "LAK" },
      { "stop_id": "TPA" },
      { "stop_id": "KIS" },
      { "stop_id": "ORL" },
      { "stop_id": "WPK" },
      { "stop_id": "DLD" },
      { "stop_id": "PAK" },
      { "stop_id": "JAX" },
      { "stop_id": "JSP" },
      { "stop_id": "SAV" },
      { "stop_id": "DNK" },
      { "stop_id": "CLB" },
      { "stop_id": "CAM" },
      { "stop_id": "HAM" },
      { "stop_id": "SOP" },
      { "stop_id": "CYN" },
      { "stop_id": "RGH" },
      { "stop_id": "YEM" },
      { "stop_id": "CHS" },
      { "stop_id": "KTR" },
      { "stop_id": "FLO" },
      { "stop_id": "DIL" },
      { "stop_id": "FAY" },
      { "stop_id": "SSM" },
      { "stop_id": "WLN" },
      { "stop_id": "RMT" },
      { "stop_id": "PTB" },
      { "stop_id": "RVR" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BWI" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "PJC" },
      { "stop_id": "NBK" },
      { "stop_id": "MET" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ]
  },
  {
    "url_slug": "carolinian-piedmont",
    "label": "Carolinian/Piedmont",
    "routes": [79, 85],
    "direction_id": 0,
    "stoptimes": [
      { "stop_id": "CLT" },
      { "stop_id": "KAN" },
      { "stop_id": "SAL" },
      { "stop_id": "HPT" },
      { "stop_id": "GRO" },
      { "stop_id": "BNC" },
      { "stop_id": "DNC" },
      { "stop_id": "CYN" },
      { "stop_id": "RGH" },
      { "stop_id": "SSM" },
      { "stop_id": "WLN" },
      { "stop_id": "RMT" },
      { "stop_id": "PTB" },
      { "stop_id": "RVR" },
      { "stop_id": "FBG" },
      { "stop_id": "QAN" },
      { "stop_id": "ALX" },
      { "stop_id": "WAS" },
      { "stop_id": "BAL" },
      { "stop_id": "WIL" },
      { "stop_id": "PHL" },
      { "stop_id": "TRE" },
      { "stop_id": "NWK" },
      { "stop_id": "NYP" }
    ]
  },
];
